import type { ApiEntry } from '../types';
import {
  createEntry,
  deprecated,
  errorSpec,
  type CanonicalImportPath,
  type SymbolSpec,
} from './shared';

const MODELS = '@sdcorejs/utils/models' as const;
const CONSTANTS = '@sdcorejs/utils/constants' as const;
const ERRORS = '@sdcorejs/utils/errors' as const;

const TYPE_ONLY_RUNTIME_EN = 'This export exists only in TypeScript declarations and is erased from emitted JavaScript.';
const TYPE_ONLY_RUNTIME_VI = 'Export này chỉ tồn tại trong khai báo TypeScript và bị xóa khỏi JavaScript sau khi biên dịch.';
const TYPE_ONLY_SECURITY_EN = 'A static type does not validate values received at runtime; validate untrusted input at the boundary.';
const TYPE_ONLY_SECURITY_VI = 'Kiểu tĩnh không kiểm tra giá trị nhận được khi chạy; hãy xác thực dữ liệu không tin cậy tại biên hệ thống.';

const typeBoundary = (
  runtimeEn: string,
  runtimeVi: string,
  securityEn: string,
  securityVi: string,
) => ({
  runtimeEn: [TYPE_ONLY_RUNTIME_EN, runtimeEn],
  runtimeVi: [TYPE_ONLY_RUNTIME_VI, runtimeVi],
  securityEn: [TYPE_ONLY_SECURITY_EN, securityEn],
  securityVi: [TYPE_ONLY_SECURITY_VI, securityVi],
});

const modelSpecs = [
  {
    symbol: 'NestedKeyOf',
    kind: 'type',
    pageId: 'api-models-types',
    importPath: MODELS,
    signature: "type NestedKeyOf<ObjectType, Depth extends number[] = []> = Depth['length'] extends 4 ? never : ObjectType extends object ? { [Key in keyof ObjectType & string]: ObjectType[Key] extends string | number | boolean | null | undefined | Date | Function ? Key : ObjectType[Key] extends Array<any> ? Key : ObjectType[Key] extends object ? Key | `${Key}.${NestedKeyOf<ObjectType[Key], [...Depth, 1]>}` : Key }[keyof ObjectType & string] : string",
    en: 'Builds a union of dot-separated property paths, descending through object properties to four levels while treating arrays and primitive leaves as terminal.',
    vi: 'Tạo union các đường dẫn thuộc tính phân tách bằng dấu chấm, đi sâu tối đa bốn cấp qua object và coi mảng cùng giá trị nguyên thủy là điểm dừng.',
    returnsEn: 'A compile-time union of valid parent and nested property paths for ObjectType.',
    returnsVi: 'Union tại thời điểm biên dịch gồm các đường dẫn thuộc tính cha và lồng nhau hợp lệ của ObjectType.',
    ...typeBoundary(
      'The depth tuple is an implementation guard; callers normally supply only ObjectType.',
      'Tuple độ sâu là cơ chế bảo vệ nội bộ; bên gọi thường chỉ truyền ObjectType.',
      'Generated path types do not make a runtime path safe; path-based helpers still reject malformed, accessor, inherited, and prototype-sensitive paths.',
      'Kiểu đường dẫn được sinh ra không làm đường dẫn runtime trở nên an toàn; helper vẫn từ chối đường dẫn sai, accessor, thuộc tính kế thừa và segment nhạy cảm với prototype.',
    ),
    exampleIds: ['safe-objects'],
  },
  {
    symbol: 'Operator',
    kind: 'type',
    pageId: 'api-models-types',
    importPath: MODELS,
    signature: 'type Operator = OperatorHasData | OperatorNoData',
    en: 'Union of every comparison and null-presence operator accepted by the filter model.',
    vi: 'Union của toàn bộ toán tử so sánh và kiểm tra null được mô hình filter chấp nhận.',
    returnsEn: 'One of the supported value-bearing or value-free operator literals.',
    returnsVi: 'Một literal toán tử được hỗ trợ, có hoặc không yêu cầu dữ liệu so sánh.',
    ...typeBoundary(
      'Logical group operators AND and OR belong to FilterAndOr rather than this union.',
      'Toán tử nhóm logic AND và OR thuộc FilterAndOr, không nằm trong union này.',
      'Do not trust a string merely because it was cast to Operator; validate external filter definitions with FilterUtilities.validateFilter.',
      'Không tin một chuỗi chỉ vì đã ép kiểu Operator; hãy kiểm tra filter bên ngoài bằng FilterUtilities.validateFilter.',
    ),
    exampleIds: ['strict-filters'],
  },
  {
    symbol: 'OperatorHasData',
    kind: 'type',
    pageId: 'api-models-types',
    importPath: MODELS,
    signature: "type OperatorHasData = 'EQUAL' | 'NOT_EQUAL' | 'CONTAIN' | 'NOT_CONTAIN' | 'IN' | 'NOT_IN' | 'START_WITH' | 'NOT_START_WITH' | 'END_WITH' | 'NOT_END_WITH' | 'GREATER_THAN' | 'LESS_THAN' | 'GREATER_OR_EQUAL' | 'LESS_OR_EQUAL' | 'BETWEEN'",
    en: 'Lists filter operators that require a comparison operand, including membership, string, ordering, and inclusive range operations.',
    vi: 'Liệt kê các toán tử filter cần toán hạng so sánh, gồm membership, chuỗi, thứ tự và khoảng đóng.',
    returnsEn: 'A value-bearing filter operator literal.',
    returnsVi: 'Một literal toán tử filter có dữ liệu.',
    ...typeBoundary(
      'BETWEEN uses FilterBetween; the other literals use a FilterHasData variant.',
      'BETWEEN dùng FilterBetween; các literal còn lại dùng một biến thể FilterHasData.',
      'Operand shape and coercion rules are enforced only by strict runtime filter validation.',
      'Hình dạng toán hạng và quy tắc ép kiểu chỉ được thực thi bởi kiểm tra filter nghiêm ngặt lúc chạy.',
    ),
    exampleIds: ['strict-filters'],
  },
  {
    symbol: 'OperatorNoData',
    kind: 'type',
    pageId: 'api-models-types',
    importPath: MODELS,
    signature: "type OperatorNoData = 'NULL' | 'NOT_NULL'",
    en: 'Restricts filters that test whether a field is nullish or present without a comparison operand.',
    vi: 'Giới hạn filter kiểm tra field nullish hoặc hiện hữu mà không cần toán hạng so sánh.',
    returnsEn: 'The NULL or NOT_NULL operator literal.',
    returnsVi: 'Literal toán tử NULL hoặc NOT_NULL.',
    ...typeBoundary(
      'Missing properties follow MatchOptions.missingValuePolicy; the default policy treats them as nullish.',
      'Thuộc tính bị thiếu tuân theo MatchOptions.missingValuePolicy; mặc định được xem là nullish.',
      'Presence tests in client code are not authorization checks and must be re-enforced by a trusted server.',
      'Kiểm tra sự hiện hữu phía client không phải kiểm soát phân quyền và phải được thực thi lại ở server tin cậy.',
    ),
    exampleIds: ['strict-filters'],
  },
  {
    symbol: 'Filter',
    kind: 'type',
    pageId: 'api-models-types',
    importPath: MODELS,
    signature: 'type Filter<T = any> = FilterHasData<T> | FilterBetween<T> | FilterNoData<T> | FilterAndOr<T>',
    en: 'Discriminated union for single-value comparisons, inclusive ranges, null checks, and nested AND/OR groups.',
    vi: 'Union phân biệt cho so sánh đơn trị, khoảng đóng, kiểm tra null và nhóm AND/OR lồng nhau.',
    returnsEn: 'A filter definition parameterized by the entity type T.',
    returnsVi: 'Định nghĩa filter được tham số hóa theo kiểu entity T.',
    ...typeBoundary(
      'T defaults to any for compatibility; supply the entity type to obtain checked field paths.',
      'T mặc định là any để tương thích; hãy truyền kiểu entity để kiểm tra đường dẫn field.',
      'Treat deserialized filters as unknown and pass them to validateFilter before evaluation; client filtering never enforces access control.',
      'Coi filter deserialize là unknown và truyền qua validateFilter trước khi đánh giá; filter phía client không bao giờ thực thi kiểm soát truy cập.',
    ),
    exampleIds: ['strict-filters'],
  },
  {
    symbol: 'FilterDataType',
    kind: 'type',
    pageId: 'api-models-types',
    importPath: MODELS,
    signature: "type FilterDataType = 'absolute' | 'field' | 'date-today' | 'date-relative'",
    en: 'Selects whether a single-value operand is a literal, another field, today, or a relative date.',
    vi: 'Chọn toán hạng đơn trị là literal, field khác, hôm nay hay ngày tương đối.',
    returnsEn: 'A discriminator used beside the data property; omission means absolute.',
    returnsVi: 'Discriminator đặt cạnh thuộc tính data; bỏ trống có nghĩa absolute.',
    ...typeBoundary(
      'Each discriminator selects a distinct FilterHasData variant and operand shape.',
      'Mỗi discriminator chọn một biến thể FilterHasData và hình dạng toán hạng riêng.',
      'Runtime validation rejects mismatched discriminators and operand shapes instead of guessing.',
      'Kiểm tra runtime từ chối discriminator và toán hạng không khớp thay vì suy đoán.',
    ),
    exampleIds: ['strict-filters'],
  },
  {
    symbol: 'FilterTimestampUnit',
    kind: 'type',
    pageId: 'api-models-types',
    importPath: MODELS,
    signature: "type FilterTimestampUnit = 'seconds' | 'milliseconds'",
    en: 'Declares the unit of numeric timestamps used by date-aware filter comparison.',
    vi: 'Khai báo đơn vị timestamp dạng số dùng trong so sánh filter có nhận biết ngày.',
    returnsEn: 'The explicit seconds or milliseconds unit.',
    returnsVi: 'Đơn vị seconds hoặc milliseconds tường minh.',
    ...typeBoundary(
      'A filter-level unit overrides evaluator-level timestamp options for that field.',
      'Đơn vị ở từng filter ghi đè tùy chọn timestamp cấp evaluator cho field đó.',
      'Explicit units prevent ambiguous magnitude inference, especially for negative and pre-2001 millisecond timestamps.',
      'Đơn vị tường minh tránh suy đoán độ lớn mơ hồ, đặc biệt với timestamp âm và millisecond trước năm 2001.',
    ),
    exampleIds: ['strict-filters'],
  },
  {
    symbol: 'DateRelative',
    kind: 'interface',
    pageId: 'api-models-types',
    importPath: MODELS,
    signature: "interface DateRelative { amount: number; direction: 'previous' | 'next'; unit: 'hour' | 'day' | 'week' | 'month' }",
    en: 'Describes a relative date operand as a positive offset magnitude, direction, and calendar/time unit.',
    vi: 'Mô tả toán hạng ngày tương đối bằng độ lớn offset dương, hướng và đơn vị lịch/thời gian.',
    parameters: [
      { name: 'amount', type: 'number', en: 'Positive safe-integer offset magnitude; runtime validation requires at least 1.', vi: 'Độ lớn offset là số nguyên an toàn dương; kiểm tra runtime yêu cầu tối thiểu 1.' },
      { name: 'direction', type: "'previous' | 'next'", en: 'Moves into the past or future.', vi: 'Di chuyển về quá khứ hoặc tương lai.' },
      { name: 'unit', type: "'hour' | 'day' | 'week' | 'month'", en: 'Offset unit.', vi: 'Đơn vị offset.' },
    ],
    returnsEn: 'A relative-date descriptor consumed by date-relative filters.',
    returnsVi: 'Mô tả ngày tương đối được filter date-relative sử dụng.',
    ...typeBoundary(
      'Hour offsets anchor at now; day, week, and month offsets anchor at the start of the current day.',
      'Offset theo giờ neo tại hiện tại; ngày, tuần và tháng neo tại đầu ngày hiện tại.',
      'Validate amount and calendar semantics before accepting user-authored filter JSON.',
      'Kiểm tra amount và ngữ nghĩa lịch trước khi chấp nhận JSON filter do người dùng tạo.',
    ),
    exampleIds: ['strict-filters'],
  },
  {
    symbol: 'FilterLiteral',
    kind: 'type',
    pageId: 'api-models-types',
    importPath: MODELS,
    signature: 'type FilterLiteral = string | number | boolean | Date | null | undefined | Array<string | number | boolean | Date | null | undefined>',
    en: 'Defines the literal scalar and array values accepted by absolute single-value filters.',
    vi: 'Định nghĩa các giá trị literal vô hướng và mảng được filter đơn trị absolute chấp nhận.',
    returnsEn: 'A supported literal operand or a flat array of supported literals.',
    returnsVi: 'Một toán hạng literal được hỗ trợ hoặc mảng phẳng các literal được hỗ trợ.',
    ...typeBoundary(
      'The union describes source types; operator-specific rules still distinguish scalar and array operands.',
      'Union mô tả kiểu nguồn; quy tắc theo từng operator vẫn phân biệt toán hạng vô hướng và mảng.',
      'Strict validation rejects NaN, infinity, malformed dates, and incorrect IN/BETWEEN shapes even when a cast bypasses TypeScript.',
      'Kiểm tra nghiêm ngặt từ chối NaN, vô cực, ngày sai và hình dạng IN/BETWEEN không đúng ngay cả khi ép kiểu vượt TypeScript.',
    ),
    exampleIds: ['strict-filters'],
  },
  {
    symbol: 'FilterHasDataAbsolute',
    kind: 'type',
    pageId: 'api-models-types',
    importPath: MODELS,
    signature: "type FilterHasDataAbsolute<T = any> = (FilterHasDataBase<T, 'IN' | 'NOT_IN'> & { dataType?: 'absolute'; data: FilterMembershipLiteral }) | (FilterHasDataBase<T, Exclude<OperatorHasData, 'BETWEEN' | 'IN' | 'NOT_IN'>> & { dataType?: 'absolute'; data: FilterScalarLiteral })",
    en: 'Represents a non-BETWEEN filter whose right-hand operand is a literal value.',
    vi: 'Biểu diễn filter không phải BETWEEN với toán hạng bên phải là giá trị literal.',
    properties: [
      { name: 'field', type: 'NestedKeyOf<T>', en: 'Dot-notation path of the field to filter.', vi: 'Đường dẫn dấu chấm của field cần lọc.' },
      { name: 'operator', type: "Exclude<OperatorHasData, 'BETWEEN'>", en: 'Membership operators require array data; every other operator requires a scalar literal.', vi: 'Operator membership yêu cầu data dạng mảng; mọi operator còn lại yêu cầu literal vô hướng.' },
      { name: 'timestampUnit', type: 'FilterTimestampUnit', optional: true, en: 'Unit for numeric date values on this filter.', vi: 'Đơn vị cho giá trị ngày dạng số của filter này.' },
      { name: 'dataType', type: "'absolute'", optional: true, defaultValue: "'absolute'", en: 'Optional discriminator; omission selects literal behavior.', vi: 'Discriminator tùy chọn; bỏ trống chọn hành vi literal.' },
      { name: 'data', type: 'FilterMembershipLiteral | FilterScalarLiteral', en: 'Array candidates for IN/NOT_IN, otherwise one scalar literal.', vi: 'Mảng ứng viên cho IN/NOT_IN, nếu không là một literal vô hướng.' },
    ],
    returnsEn: 'A literal-comparison filter definition.',
    returnsVi: 'Định nghĩa filter so sánh literal.',
    ...typeBoundary(
      'IN and NOT_IN require array data; other operators use scalar data, while BETWEEN has its own model.',
      'IN và NOT_IN yêu cầu data dạng mảng; operator khác dùng scalar, còn BETWEEN có model riêng.',
      'Run validateFilter before evaluation so malformed operands cannot be treated as valid configuration.',
      'Chạy validateFilter trước khi đánh giá để toán hạng sai không bị coi là cấu hình hợp lệ.',
    ),
    exampleIds: ['strict-filters'],
  },
  {
    symbol: 'FilterHasDataField',
    kind: 'interface',
    pageId: 'api-models-types',
    importPath: MODELS,
    signature: "interface FilterHasDataField<T = any> { field: NestedKeyOf<T>; operator: Exclude<OperatorHasData, 'BETWEEN'>; timestampUnit?: FilterTimestampUnit; dataType: 'field'; data: NestedKeyOf<T> }",
    en: 'Compares one entity field with another field selected by a dot-notation path.',
    vi: 'So sánh một field của entity với field khác được chọn bằng đường dẫn dấu chấm.',
    properties: [
      { name: 'field', type: 'NestedKeyOf<T>', en: 'Dot-notation path of the field to filter.', vi: 'Đường dẫn dấu chấm của field cần lọc.' },
      { name: 'operator', type: "Exclude<OperatorHasData, 'BETWEEN'>", en: 'Single-value operator, including IN and NOT_IN for field-to-field array membership.', vi: 'Operator đơn trị, gồm IN và NOT_IN cho membership field-với-field dạng mảng.' },
      { name: 'timestampUnit', type: 'FilterTimestampUnit', optional: true, en: 'Unit for numeric date values on this filter.', vi: 'Đơn vị cho giá trị ngày dạng số của filter này.' },
      { name: 'dataType', type: "'field'", en: 'Discriminator selecting field-to-field behavior.', vi: 'Discriminator chọn hành vi so sánh field-với-field.' },
      { name: 'data', type: 'NestedKeyOf<T>', en: 'Dot-notation path of the field used as the operand.', vi: 'Đường dẫn dấu chấm của field dùng làm toán hạng.' },
    ],
    returnsEn: 'A field-to-field comparison definition.',
    returnsVi: 'Định nghĩa so sánh field với field.',
    ...typeBoundary(
      'Both field paths are resolved as own data properties; MatchOptions can declare their value types and timestamp units.',
      'Cả hai đường dẫn field được resolve từ own data property; MatchOptions có thể khai báo kiểu giá trị và đơn vị timestamp.',
      'Runtime path validation rejects inherited values, accessors, malformed paths, and prototype-sensitive segments.',
      'Kiểm tra đường dẫn runtime từ chối giá trị kế thừa, accessor, đường dẫn sai và segment nhạy cảm với prototype.',
    ),
    exampleIds: ['strict-filters'],
  },
  {
    symbol: 'FilterHasDataToday',
    kind: 'interface',
    pageId: 'api-models-types',
    importPath: MODELS,
    signature: "interface FilterHasDataToday<T = any> { field: NestedKeyOf<T>; operator: Exclude<OperatorHasData, 'BETWEEN' | 'IN' | 'NOT_IN'>; timestampUnit?: FilterTimestampUnit; dataType: 'date-today'; data: 'TODAY' }",
    en: 'Uses the start of today as the right-hand operand for a date-aware comparison.',
    vi: 'Dùng đầu ngày hôm nay làm toán hạng bên phải cho so sánh có nhận biết ngày.',
    properties: [
      { name: 'field', type: 'NestedKeyOf<T>', en: 'Dot-notation path of the date field to filter.', vi: 'Đường dẫn dấu chấm của field ngày cần lọc.' },
      { name: 'operator', type: "Exclude<OperatorHasData, 'BETWEEN' | 'IN' | 'NOT_IN'>", en: 'Scalar comparison operator; membership and BETWEEN are excluded.', vi: 'Operator so sánh vô hướng; loại trừ membership và BETWEEN.' },
      { name: 'timestampUnit', type: 'FilterTimestampUnit', optional: true, en: 'Unit for numeric date values on this filter.', vi: 'Đơn vị cho giá trị ngày dạng số của filter này.' },
      { name: 'dataType', type: "'date-today'", en: 'Discriminator selecting the start-of-today operand.', vi: 'Discriminator chọn toán hạng đầu ngày hôm nay.' },
      { name: 'data', type: "'TODAY'", en: 'Fixed sentinel resolved at evaluation time.', vi: 'Sentinel cố định được resolve khi đánh giá.' },
    ],
    returnsEn: 'A date-today filter carrying the fixed TODAY sentinel.',
    returnsVi: 'Filter date-today mang sentinel cố định TODAY.',
    ...typeBoundary(
      'Today is computed from MatchOptions.now when supplied, otherwise from the current local clock.',
      'Hôm nay được tính từ MatchOptions.now nếu có, nếu không dùng đồng hồ local hiện tại.',
      'Inject a deterministic now value for reproducible tests and time-sensitive business workflows.',
      'Truyền now xác định để test và workflow nhạy thời gian có kết quả lặp lại được.',
    ),
    exampleIds: ['strict-filters'],
  },
  {
    symbol: 'FilterHasDataRelative',
    kind: 'interface',
    pageId: 'api-models-types',
    importPath: MODELS,
    signature: "interface FilterHasDataRelative<T = any> { field: NestedKeyOf<T>; operator: Exclude<OperatorHasData, 'BETWEEN' | 'IN' | 'NOT_IN'>; timestampUnit?: FilterTimestampUnit; dataType: 'date-relative'; data: DateRelative }",
    en: 'Uses a DateRelative descriptor as the right-hand operand of a date comparison.',
    vi: 'Dùng mô tả DateRelative làm toán hạng bên phải của phép so sánh ngày.',
    properties: [
      { name: 'field', type: 'NestedKeyOf<T>', en: 'Dot-notation path of the date field to filter.', vi: 'Đường dẫn dấu chấm của field ngày cần lọc.' },
      { name: 'operator', type: "Exclude<OperatorHasData, 'BETWEEN' | 'IN' | 'NOT_IN'>", en: 'Scalar comparison operator; membership and BETWEEN are excluded.', vi: 'Operator so sánh vô hướng; loại trừ membership và BETWEEN.' },
      { name: 'timestampUnit', type: 'FilterTimestampUnit', optional: true, en: 'Unit for numeric date values on this filter.', vi: 'Đơn vị cho giá trị ngày dạng số của filter này.' },
      { name: 'dataType', type: "'date-relative'", en: 'Discriminator selecting a relative-date operand.', vi: 'Discriminator chọn toán hạng ngày tương đối.' },
      { name: 'data', type: 'DateRelative', en: 'Relative-date descriptor resolved during evaluation.', vi: 'Mô tả ngày tương đối được resolve khi đánh giá.' },
    ],
    returnsEn: 'A relative-date filter definition.',
    returnsVi: 'Định nghĩa filter ngày tương đối.',
    ...typeBoundary(
      'The descriptor is resolved at evaluation time using MatchOptions.now or the local current time.',
      'Mô tả được resolve khi đánh giá bằng MatchOptions.now hoặc thời gian local hiện tại.',
      'Strict validation bounds the offset and rejects malformed descriptors before date arithmetic.',
      'Kiểm tra nghiêm ngặt giới hạn offset và từ chối mô tả sai trước khi tính toán ngày.',
    ),
    exampleIds: ['strict-filters'],
  },
  {
    symbol: 'FilterHasData',
    kind: 'type',
    pageId: 'api-models-types',
    importPath: MODELS,
    signature: 'type FilterHasData<T = any> = FilterHasDataAbsolute<T> | FilterHasDataField<T> | FilterHasDataToday<T> | FilterHasDataRelative<T>',
    en: 'Combines all non-BETWEEN filter variants that carry a comparison operand.',
    vi: 'Kết hợp toàn bộ biến thể filter có toán hạng so sánh, ngoại trừ BETWEEN.',
    returnsEn: 'A discriminated single-value filter union.',
    returnsVi: 'Union filter đơn trị có discriminator.',
    ...typeBoundary(
      'The dataType sibling determines how data is interpreted; omission selects FilterHasDataAbsolute.',
      'Thuộc tính dataType cạnh data quyết định cách diễn giải; bỏ trống chọn FilterHasDataAbsolute.',
      'Validate external definitions instead of branching only on an untrusted dataType value.',
      'Kiểm tra định nghĩa bên ngoài thay vì chỉ rẽ nhánh theo dataType không tin cậy.',
    ),
    exampleIds: ['strict-filters'],
  },
  {
    symbol: 'FilterBetween',
    kind: 'interface',
    pageId: 'api-models-types',
    importPath: MODELS,
    signature: "interface FilterBetween<T = any> { field: NestedKeyOf<T>; operator: 'BETWEEN'; timestampUnit?: FilterTimestampUnit; data: { from: string | number | Date; to: string | number | Date } }",
    en: 'Defines an inclusive lower-to-upper range comparison for a single field.',
    vi: 'Định nghĩa so sánh khoảng đóng từ cận dưới đến cận trên cho một field.',
    properties: [
      { name: 'field', type: 'NestedKeyOf<T>', en: 'Dot-notation path of the field to filter.', vi: 'Đường dẫn dấu chấm của field cần lọc.' },
      { name: 'operator', type: "'BETWEEN'", en: 'Fixed inclusive-range operator.', vi: 'Operator khoảng đóng cố định.' },
      { name: 'timestampUnit', type: 'FilterTimestampUnit', optional: true, en: 'Overrides evaluator timestamp options for numeric date bounds.', vi: 'Ghi đè tùy chọn timestamp của evaluator cho cận ngày dạng số.' },
      { name: 'data', type: '{ from: string | number | Date; to: string | number | Date }', en: 'Inclusive lower and upper bounds.', vi: 'Cận dưới và cận trên có bao gồm.' },
    ],
    returnsEn: 'An inclusive BETWEEN filter definition.',
    returnsVi: 'Định nghĩa filter BETWEEN bao gồm hai cận.',
    ...typeBoundary(
      'Strict validation requires comparable, correctly ordered bounds and an explicit unit for numeric dates.',
      'Kiểm tra nghiêm ngặt yêu cầu hai cận so sánh được, đúng thứ tự và đơn vị tường minh cho ngày dạng số.',
      'Reject user-authored reversed or malformed ranges rather than swapping or coercing them silently.',
      'Từ chối khoảng do người dùng tạo bị đảo hoặc sai thay vì tự đổi chỗ hay ép kiểu âm thầm.',
    ),
    exampleIds: ['strict-filters'],
  },
  {
    symbol: 'FilterNoData',
    kind: 'interface',
    pageId: 'api-models-types',
    importPath: MODELS,
    signature: "interface FilterNoData<T = any> { field: NestedKeyOf<T>; operator: 'NULL' | 'NOT_NULL' }",
    en: 'Defines a null-presence check with no data operand.',
    vi: 'Định nghĩa kiểm tra sự hiện hữu của null mà không có toán hạng data.',
    properties: [
      { name: 'field', type: 'NestedKeyOf<T>', en: 'Dot-notation path of the field to check.', vi: 'Đường dẫn dấu chấm của field cần kiểm tra.' },
      { name: 'operator', type: 'OperatorNoData', en: 'NULL or NOT_NULL presence operator.', vi: 'Operator hiện hữu NULL hoặc NOT_NULL.' },
    ],
    returnsEn: 'A NULL or NOT_NULL filter definition.',
    returnsVi: 'Định nghĩa filter NULL hoặc NOT_NULL.',
    ...typeBoundary(
      'Missing and explicit null values are distinguished only when missingValuePolicy is distinct.',
      'Giá trị bị thiếu và null tường minh chỉ được phân biệt khi missingValuePolicy là distinct.',
      'A client-side null check cannot enforce data visibility or field-level authorization.',
      'Kiểm tra null phía client không thể thực thi quyền xem dữ liệu hoặc phân quyền cấp field.',
    ),
    exampleIds: ['strict-filters'],
  },
  {
    symbol: 'FilterAndOr',
    kind: 'interface',
    pageId: 'api-models-types',
    importPath: MODELS,
    signature: "interface FilterAndOr<T = any> { operator: 'AND' | 'OR'; data: Filter<T>[] }",
    en: 'Groups child filters recursively with logical AND or OR semantics.',
    vi: 'Nhóm đệ quy các filter con theo ngữ nghĩa logic AND hoặc OR.',
    properties: [
      { name: 'operator', type: "'AND' | 'OR'", en: 'Logical operator joining every child.', vi: 'Operator logic nối mọi phần tử con.' },
      { name: 'data', type: 'Filter<T>[]', en: 'Child filters, which may include nested logical groups.', vi: 'Các filter con, có thể gồm nhóm logic lồng nhau.' },
    ],
    returnsEn: 'A logical filter group containing zero or more child definitions.',
    returnsVi: 'Nhóm filter logic chứa không hoặc nhiều định nghĩa con.',
    ...typeBoundary(
      'Runtime validation detects cycles and defaults the maximum logical nesting depth to 32.',
      'Kiểm tra runtime phát hiện chu trình và mặc định giới hạn độ sâu nhóm logic là 32.',
      'Bound and validate externally supplied filter graphs before evaluation to avoid cyclic or excessively deep input.',
      'Giới hạn và kiểm tra graph filter bên ngoài trước khi đánh giá để tránh input có chu trình hoặc quá sâu.',
    ),
    exampleIds: ['strict-filters'],
  },
  {
    symbol: 'FilterFieldType',
    kind: 'type',
    pageId: 'api-models-types',
    importPath: MODELS,
    signature: "type FilterFieldType = 'string' | 'number' | 'boolean' | 'date'",
    en: 'Declares the comparison type of a field so client-side filter evaluation can avoid ambiguous inference.',
    vi: 'Khai báo kiểu so sánh của field để việc đánh giá filter phía client tránh suy đoán mơ hồ.',
    returnsEn: 'A supported field coercion category.',
    returnsVi: 'Một nhóm ép kiểu field được hỗ trợ.',
    ...typeBoundary(
      'Values are used through MatchOptions.fieldTypes to normalize both sides consistently.',
      'Giá trị được dùng qua MatchOptions.fieldTypes để chuẩn hóa nhất quán cả hai vế.',
      'Declared field types improve deterministic comparison but do not validate an entity schema or authorize access.',
      'Kiểu field khai báo giúp so sánh xác định nhưng không kiểm tra schema entity hoặc cấp quyền truy cập.',
    ),
    exampleIds: ['strict-filters'],
  },
  {
    symbol: 'ValidatedFilter',
    kind: 'type',
    pageId: 'api-models-types',
    importPath: MODELS,
    signature: 'type ValidatedFilter<T = any> = Filter<T> & { readonly [validatedFilterBrand]: true }',
    en: 'Opaque branded filter type returned after runtime shape, operand, path, depth, and cycle validation succeeds.',
    vi: 'Kiểu filter opaque có brand, được trả về sau khi kiểm tra runtime về hình dạng, toán hạng, đường dẫn, độ sâu và chu trình thành công.',
    returnsEn: 'A Filter<T> carrying an internal compile-time validation brand.',
    returnsVi: 'Filter<T> mang brand kiểm tra nội bộ tại thời điểm biên dịch.',
    ...typeBoundary(
      'Create this value through FilterUtilities.validateFilter; the unique brand is not exported for ordinary construction.',
      'Tạo giá trị này qua FilterUtilities.validateFilter; unique brand không được export để tự tạo thông thường.',
      'A type assertion can forge any TypeScript brand, so do not accept a cast as evidence that untrusted data was validated.',
      'Ép kiểu có thể giả mạo mọi brand TypeScript, vì vậy không coi cast là bằng chứng dữ liệu không tin cậy đã được kiểm tra.',
    ),
    exampleIds: ['strict-filters'],
  },
  {
    symbol: 'MatchOptions',
    kind: 'interface',
    pageId: 'api-models-types',
    importPath: MODELS,
    signature: "interface MatchOptions<T = any> { fieldTypes?: Partial<Record<NestedKeyOf<T> & string, FilterFieldType>>; timestampUnit?: FilterTimestampUnit; timestampUnits?: Partial<Record<NestedKeyOf<T> & string, FilterTimestampUnit>>; legacyTimestampInference?: boolean; maxDepth?: number; maxPathDepth?: number; missingValuePolicy?: 'nullish' | 'distinct'; now?: Date }",
    en: 'Configures deterministic type coercion, timestamp interpretation, safety bounds, missing-value policy, and reference time for filter validation and evaluation.',
    vi: 'Cấu hình ép kiểu xác định, cách hiểu timestamp, giới hạn an toàn, chính sách giá trị thiếu và thời điểm tham chiếu cho kiểm tra/đánh giá filter.',
    parameters: [
      { name: 'fieldTypes', type: 'Partial<Record<NestedKeyOf<T> & string, FilterFieldType>>', optional: true, en: 'Declared comparison type by field path.', vi: 'Kiểu so sánh khai báo theo đường dẫn field.' },
      { name: 'timestampUnit', type: 'FilterTimestampUnit', optional: true, en: 'Default unit for numeric date values.', vi: 'Đơn vị mặc định cho giá trị ngày dạng số.' },
      { name: 'timestampUnits', type: 'Partial<Record<NestedKeyOf<T> & string, FilterTimestampUnit>>', optional: true, en: 'Per-field numeric timestamp units; own data properties are read.', vi: 'Đơn vị timestamp theo từng field; chỉ đọc own data property.' },
      { name: 'legacyTimestampInference', type: 'boolean', optional: true, defaultValue: 'false', en: 'Deprecated opt-in for the v1.x magnitude heuristic.', vi: 'Tùy chọn deprecated để bật lại heuristic độ lớn v1.x.' },
      { name: 'maxDepth', type: 'number', optional: true, defaultValue: '32', en: 'Maximum logical-filter nesting depth.', vi: 'Độ sâu lồng nhóm filter logic tối đa.' },
      { name: 'maxPathDepth', type: 'number', optional: true, defaultValue: '32', en: 'Maximum property-path segment count.', vi: 'Số segment đường dẫn thuộc tính tối đa.' },
      { name: 'missingValuePolicy', type: "'nullish' | 'distinct'", optional: true, defaultValue: "'nullish'", en: 'Whether a missing path satisfies NULL.', vi: 'Quy định đường dẫn bị thiếu có thỏa NULL hay không.' },
      { name: 'now', type: 'Date', optional: true, defaultValue: 'new Date()', en: 'Reference time for today and relative-date operands.', vi: 'Thời điểm tham chiếu cho toán hạng hôm nay và ngày tương đối.' },
    ],
    returnsEn: 'An options object consumed by strict filter APIs.',
    returnsVi: 'Object tùy chọn được các API filter nghiêm ngặt sử dụng.',
    ...typeBoundary(
      'Per-filter timestampUnit takes precedence over timestampUnits and the global timestampUnit.',
      'timestampUnit trên từng filter ưu tiên hơn timestampUnits và timestampUnit toàn cục.',
      'Keep legacyTimestampInference disabled for new code; magnitude guessing can reinterpret legitimate pre-2001 millisecond timestamps.',
      'Giữ legacyTimestampInference tắt với code mới; suy đoán độ lớn có thể diễn giải sai timestamp millisecond hợp lệ trước năm 2001.',
    ),
    exampleIds: ['strict-filters'],
  },
  {
    symbol: 'Order',
    kind: 'interface',
    pageId: 'api-models-types',
    importPath: MODELS,
    signature: "interface Order<T = any> { field: NestedKeyOf<T>; direction: 'ASC' | 'DESC' }",
    en: 'Describes one typed dot-path sort criterion and its ascending or descending direction.',
    vi: 'Mô tả một tiêu chí sắp xếp theo đường dẫn có kiểu và hướng tăng hoặc giảm.',
    properties: [
      { name: 'field', type: 'NestedKeyOf<T>', en: 'Dot-notation path of the field to sort.', vi: 'Đường dẫn dấu chấm của field cần sắp xếp.' },
      { name: 'direction', type: "'ASC' | 'DESC'", en: 'Ascending or descending direction.', vi: 'Hướng tăng dần hoặc giảm dần.' },
    ],
    returnsEn: 'A single sort descriptor for query and paging requests.',
    returnsVi: 'Một mô tả sắp xếp cho request truy vấn và phân trang.',
    ...typeBoundary(
      'Multiple Order values are applied in array order by the receiving endpoint.',
      'Nhiều giá trị Order được endpoint nhận áp dụng theo thứ tự trong mảng.',
      'The type does not whitelist server-side sortable columns at runtime; enforce an allowlist in the trusted query layer.',
      'Kiểu này không whitelist cột được phép sort ở server lúc chạy; hãy thực thi allowlist trong tầng truy vấn tin cậy.',
    ),
    exampleIds: ['paging-zero'],
  },
  {
    symbol: 'QueryReq',
    kind: 'interface',
    pageId: 'api-models-types',
    importPath: MODELS,
    signature: 'interface QueryReq<T = any> { filters?: Filter<T>[]; fields?: NestedKeyOf<T>[] }',
    en: 'Base query request for optional filters and sparse field projection without pagination.',
    vi: 'Request truy vấn cơ sở cho filter tùy chọn và chọn tập field thưa, không kèm phân trang.',
    parameters: [
      { name: 'filters', type: 'Filter<T>[]', optional: true, en: 'Filter definitions applied by the endpoint.', vi: 'Các định nghĩa filter được endpoint áp dụng.' },
      { name: 'fields', type: 'NestedKeyOf<T>[]', optional: true, en: 'Requested dot-path fields in the response.', vi: 'Các field dạng đường dẫn dấu chấm được yêu cầu trong response.' },
    ],
    returnsEn: 'A query request shape parameterized by entity type T.',
    returnsVi: 'Hình dạng request truy vấn được tham số hóa theo entity T.',
    ...typeBoundary(
      'PagingReq extends this interface with zero-based page controls and sort orders.',
      'PagingReq mở rộng interface này bằng điều khiển trang zero-based và thứ tự sort.',
      'Server implementations must validate filters, projection allowlists, and authorization independently of client types.',
      'Server phải tự kiểm tra filter, allowlist field projection và phân quyền, độc lập với kiểu phía client.',
    ),
    exampleIds: ['paging-zero'],
  },
  {
    symbol: 'PagingReq',
    kind: 'interface',
    pageId: 'api-models-types',
    importPath: MODELS,
    signature: 'interface PagingReq<T = any> extends QueryReq<T> { pageSize?: number; pageNumber?: number; orders?: Order<T>[] }',
    en: 'Adds optional zero-based page controls and ordered sort criteria to QueryReq.',
    vi: 'Bổ sung điều khiển trang zero-based tùy chọn và tiêu chí sort có thứ tự vào QueryReq.',
    properties: [
      { name: 'filters', type: 'Filter<T>[]', optional: true, en: 'Inherited filter definitions applied by the endpoint.', vi: 'Các định nghĩa filter kế thừa được endpoint áp dụng.' },
      { name: 'fields', type: 'NestedKeyOf<T>[]', optional: true, en: 'Inherited sparse field projection.', vi: 'Phép chiếu tập field thưa được kế thừa.' },
      { name: 'pageSize', type: 'number', optional: true, defaultValue: 'server default', en: 'Requested number of items; omission delegates to the server default.', vi: 'Số phần tử yêu cầu; bỏ trống dùng mặc định của server.' },
      { name: 'pageNumber', type: 'number', optional: true, defaultValue: 'server default', en: 'Zero-based page index; 0 is the first page.', vi: 'Chỉ số trang zero-based; 0 là trang đầu tiên.' },
      { name: 'orders', type: 'Order<T>[]', optional: true, en: 'Ordered list of sort criteria.', vi: 'Danh sách tiêu chí sort theo thứ tự.' },
    ],
    returnsEn: 'A paginated request shape whose pageNumber is always interpreted as zero-based.',
    returnsVi: 'Hình dạng request phân trang với pageNumber luôn được hiểu là zero-based.',
    ...typeBoundary(
      'Omitting pageNumber preserves a server default; supplying the first page means passing 0.',
      'Bỏ pageNumber giữ mặc định của server; truyền trang đầu tiên nghĩa là dùng 0.',
      'For one-based services, translate pageNumber + 1 only inside the transport adapter; do not introduce a page-base option into application models.',
      'Với service one-based, chỉ chuyển pageNumber + 1 trong adapter transport; không thêm tùy chọn page base vào model ứng dụng.',
    ),
    exampleIds: ['paging-zero', 'paging-one-based'],
  },
  {
    symbol: 'PagingRes',
    kind: 'interface',
    pageId: 'api-models-types',
    importPath: MODELS,
    signature: 'interface PagingRes<T = any> { items: T[]; total: number }',
    en: 'Standard response envelope containing one page of items and the total matching record count.',
    vi: 'Envelope response chuẩn chứa một trang phần tử và tổng số bản ghi phù hợp.',
    parameters: [
      { name: 'items', type: 'T[]', en: 'Items in the current page.', vi: 'Các phần tử của trang hiện tại.' },
      { name: 'total', type: 'number', en: 'Total records matching the query across all pages.', vi: 'Tổng số bản ghi phù hợp truy vấn trên mọi trang.' },
    ],
    returnsEn: 'A page payload consumed by paging helpers and application transports.',
    returnsVi: 'Payload một trang được helper phân trang và transport ứng dụng sử dụng.',
    ...typeBoundary(
      'The envelope does not include a page index; the request/callback sequence supplies that context.',
      'Envelope không chứa chỉ số trang; trình tự request/callback cung cấp ngữ cảnh đó.',
      'Validate total as a non-negative safe integer and items as an array before trusting an untyped endpoint response.',
      'Kiểm tra total là số nguyên an toàn không âm và items là mảng trước khi tin response endpoint chưa có kiểu.',
    ),
    exampleIds: ['paging-zero'],
  },
  {
    symbol: 'Size',
    kind: 'type',
    pageId: 'api-models-types',
    importPath: MODELS,
    signature: "type Size = 'sm' | 'md' | 'lg'",
    en: 'Shared small, medium, and large visual-density token.',
    vi: 'Token mật độ hiển thị dùng chung gồm nhỏ, vừa và lớn.',
    returnsEn: 'The sm, md, or lg size literal.',
    returnsVi: 'Literal kích thước sm, md hoặc lg.',
    ...typeBoundary(
      'The utility package supplies the token vocabulary, not component styling or a runtime default.',
      'Package utility chỉ cung cấp bộ token, không cung cấp style component hay mặc định runtime.',
      'Do not use a visual size token as a substitute for validation of numeric dimensions or uploaded content size.',
      'Không dùng token kích thước hiển thị thay cho kiểm tra kích thước số hoặc dung lượng nội dung upload.',
    ),
    exampleIds: ['browser-workflows'],
  },
  {
    symbol: 'Color',
    kind: 'type',
    pageId: 'api-models-types',
    importPath: MODELS,
    signature: "type Color = 'primary' | 'secondary' | 'info' | 'success' | 'warning' | 'error'",
    en: 'Semantic UI color token for actions, information, success, warnings, and errors.',
    vi: 'Token màu UI ngữ nghĩa cho hành động, thông tin, thành công, cảnh báo và lỗi.',
    returnsEn: 'A supported semantic color literal.',
    returnsVi: 'Một literal màu ngữ nghĩa được hỗ trợ.',
    ...typeBoundary(
      'Actual palette values and contrast are defined by the consuming design system.',
      'Giá trị palette và độ tương phản thực tế do design system sử dụng định nghĩa.',
      'Color alone must not convey security state or validation meaning; include text and accessible semantics.',
      'Không dùng riêng màu sắc để truyền đạt trạng thái bảo mật hay validation; cần có văn bản và ngữ nghĩa accessibility.',
    ),
    exampleIds: ['browser-workflows'],
  },
  {
    symbol: 'MaterialIconFontSet',
    kind: 'type',
    pageId: 'api-models-types',
    importPath: MODELS,
    signature: "type MaterialIconFontSet = 'material-icons' | 'material-icons-outlined' | 'material-icons-round' | 'material-icons-sharp'",
    en: 'Legacy Material Icons ligature-font family identifiers.',
    vi: 'Các định danh family font ligature Material Icons thế hệ cũ.',
    returnsEn: 'A supported legacy Material Icons font-set identifier.',
    returnsVi: 'Một định danh font set Material Icons cũ được hỗ trợ.',
    ...typeBoundary(
      'Loading the named font assets remains the responsibility of the consuming application.',
      'Ứng dụng sử dụng chịu trách nhiệm tải asset font tương ứng.',
      'Icons are visual labels; supply accessible names for interactive controls and never encode authorization only in an icon.',
      'Icon là nhãn trực quan; cần tên accessible cho control tương tác và không biểu diễn phân quyền chỉ bằng icon.',
    ),
    exampleIds: ['browser-workflows'],
  },
  {
    symbol: 'MaterialSymbolFontSet',
    kind: 'type',
    pageId: 'api-models-types',
    importPath: MODELS,
    signature: "type MaterialSymbolFontSet = 'material-symbols-outlined' | 'material-symbols-rounded' | 'material-symbols-sharp'",
    en: 'Material Symbols variable-font family identifiers for new icon integrations.',
    vi: 'Các định danh family variable font Material Symbols dành cho tích hợp icon mới.',
    returnsEn: 'A supported Material Symbols font-set identifier.',
    returnsVi: 'Một định danh font set Material Symbols được hỗ trợ.',
    ...typeBoundary(
      'This type names font families only; it does not install, preload, or configure variable-font axes.',
      'Kiểu này chỉ đặt tên family font; không cài đặt, preload hay cấu hình trục variable font.',
      'Provide accessible text for semantic icons and review any third-party font delivery policy.',
      'Cung cấp văn bản accessible cho icon có ngữ nghĩa và rà soát chính sách phân phối font bên thứ ba.',
    ),
    exampleIds: ['browser-workflows'],
  },
  {
    symbol: 'ValidationPatternType',
    kind: 'type',
    pageId: 'api-models-types',
    importPath: MODELS,
    signature: "type ValidationPatternType = 'EMAIL' | 'PHONE' | 'VN_PHONE' | 'VN_ID' | 'PASSPORT' | 'VN_ID_OR_PASSPORT' | 'TIME' | 'URL' | 'DOMAIN' | 'IPV4' | 'IPV6' | 'IMAGE_URL' | 'SLUG' | 'NUMBER' | 'INTEGER' | 'DECIMAL' | 'POSITIVE_NUMBER' | 'UUID' | 'CODE_16' | 'CODE_32' | 'HEX_COLOR' | 'BASE64'",
    en: 'Identifier union for the built-in validation-pattern catalogue.',
    vi: 'Union định danh cho danh mục pattern validation dựng sẵn.',
    returnsEn: 'One of the 22 built-in pattern identifiers.',
    returnsVi: 'Một trong 22 định danh pattern dựng sẵn.',
    ...typeBoundary(
      'UUID identifies generic UUID syntax; use the dedicated UUID v4 validator when version and RFC variant are required.',
      'UUID biểu thị cú pháp UUID chung; dùng validator UUID v4 riêng khi cần đúng version và RFC variant.',
      'Pattern identifiers describe syntax checks, not identity, ownership, content safety, or authorization.',
      'Định danh pattern chỉ mô tả kiểm tra cú pháp, không chứng minh danh tính, quyền sở hữu, độ an toàn nội dung hay phân quyền.',
    ),
    exampleIds: ['numbers-validation'],
  },
  {
    symbol: 'ValidationPattern',
    kind: 'interface',
    pageId: 'api-models-types',
    importPath: MODELS,
    signature: 'interface ValidationPattern { type: ValidationPatternType; name: string; pattern: string; errorMessage: string }',
    en: 'Pairs a built-in pattern identifier with a regex source and localization keys for its label and error message.',
    vi: 'Ghép định danh pattern dựng sẵn với nguồn regex và key bản địa hóa cho nhãn cùng thông báo lỗi.',
    parameters: [
      { name: 'type', type: 'ValidationPatternType', en: 'Stable pattern identifier.', vi: 'Định danh pattern ổn định.' },
      { name: 'name', type: 'string', en: 'Localization key for the display name.', vi: 'Key bản địa hóa cho tên hiển thị.' },
      { name: 'pattern', type: 'string', en: 'Regex source accepted by RegExp and Angular Validators.pattern.', vi: 'Nguồn regex dùng được với RegExp và Angular Validators.pattern.' },
      { name: 'errorMessage', type: 'string', en: 'Localization key for the validation failure message.', vi: 'Key bản địa hóa cho thông báo validation thất bại.' },
    ],
    returnsEn: 'Metadata for one entry in VALIDATION_PATTERNS.',
    returnsVi: 'Metadata cho một mục trong VALIDATION_PATTERNS.',
    ...typeBoundary(
      'name and errorMessage are lookup keys, not already translated display strings.',
      'name và errorMessage là key tra cứu, không phải chuỗi hiển thị đã dịch.',
      'Regex validation is a client-side syntax aid and cannot establish remote content type, identity, or trust.',
      'Validation bằng regex chỉ hỗ trợ cú pháp phía client và không chứng minh loại nội dung từ xa, danh tính hay độ tin cậy.',
    ),
    exampleIds: ['numbers-validation'],
  },
  {
    symbol: 'Language',
    kind: 'type',
    pageId: 'api-models-types',
    importPath: MODELS,
    signature: "type Language = 'vi' | 'en' | 'ja' | 'ko' | 'zh'",
    en: 'Locale-code union shared with the supported-language constant.',
    vi: 'Union mã locale dùng chung với constant danh sách ngôn ngữ được hỗ trợ.',
    returnsEn: 'Vietnamese, English, Japanese, Korean, or Simplified Chinese locale code.',
    returnsVi: 'Mã locale tiếng Việt, Anh, Nhật, Hàn hoặc Trung giản thể.',
    ...typeBoundary(
      'This application-language set is distinct from the documentation portal locale pair.',
      'Tập ngôn ngữ ứng dụng này tách biệt với cặp locale của cổng tài liệu.',
      'Validate persisted or request-provided locale strings against SUPPORTED_LANGUAGES before use.',
      'Kiểm tra chuỗi locale lưu trữ hoặc nhận từ request với SUPPORTED_LANGUAGES trước khi dùng.',
    ),
    exampleIds: ['browser-workflows'],
  },
] as const satisfies readonly SymbolSpec[];

const asyncSpecs = [
  {
    symbol: 'SubscriptionLike',
    kind: 'interface',
    pageId: 'api-validation-async',
    importPath: MODELS,
    signature: 'interface SubscriptionLike { readonly closed?: boolean; unsubscribe(): void }',
    en: 'Minimal structural cleanup contract shared by dependency-free subscribables.',
    vi: 'Contract cleanup cấu trúc tối thiểu dùng chung cho subscribable không phụ thuộc thư viện.',
    properties: [
      { name: 'closed', type: 'boolean', optional: true, readonly: true, en: 'Whether the subscription has already closed, when exposed.', vi: 'Subscription đã đóng hay chưa, khi implementation cung cấp.' },
      { name: 'unsubscribe', type: '() => void', en: 'Stops future emissions and releases resources.', vi: 'Dừng phát giá trị tiếp theo và giải phóng tài nguyên.' },
    ],
    returnsEn: 'A subscription handle with optional closed state and mandatory unsubscribe method.',
    returnsVi: 'Handle subscription có trạng thái closed tùy chọn và method unsubscribe bắt buộc.',
    ...typeBoundary(
      'RxJS Subscription values satisfy this shape, but RxJS is not imported or named in package declarations.',
      'Giá trị Subscription của RxJS phù hợp hình dạng này, nhưng package không import hay nhắc RxJS trong declaration.',
      'Cleanup may release sensitive resources; consumers should make unsubscribe idempotent and avoid exposing cleanup failures as secrets.',
      'Cleanup có thể giải phóng tài nguyên nhạy cảm; unsubscribe nên idempotent và không làm lộ bí mật qua lỗi cleanup.',
    ),
    exampleIds: ['async-rxjs'],
  },
  {
    symbol: 'ObserverLike',
    kind: 'interface',
    pageId: 'api-validation-async',
    importPath: MODELS,
    signature: 'interface ObserverLike<T> { next?(value: T): void; error?(error: unknown): void; complete?(): void }',
    en: 'Structural observer callbacks for values, terminal errors, and successful completion.',
    vi: 'Các callback observer cấu trúc cho giá trị, lỗi kết thúc và hoàn tất thành công.',
    properties: [
      { name: 'next', type: '(value: T) => void', optional: true, en: 'Receives an emitted value.', vi: 'Nhận một giá trị được phát.' },
      { name: 'error', type: '(error: unknown) => void', optional: true, en: 'Receives a terminal source error.', vi: 'Nhận lỗi kết thúc từ nguồn.' },
      { name: 'complete', type: '() => void', optional: true, en: 'Receives successful completion.', vi: 'Nhận tín hiệu hoàn tất thành công.' },
    ],
    returnsEn: 'An optional-callback observer shape parameterized by emitted value T.',
    returnsVi: 'Hình dạng observer có callback tùy chọn, tham số hóa theo giá trị phát T.',
    ...typeBoundary(
      'Every callback is optional so subscribe() and partial observer forms remain valid.',
      'Mọi callback đều tùy chọn để dạng subscribe() và partial observer vẫn hợp lệ.',
      'Treat error values as unknown and redact sensitive data before logging or presenting them.',
      'Coi giá trị error là unknown và ẩn dữ liệu nhạy cảm trước khi log hoặc hiển thị.',
    ),
    exampleIds: ['async-rxjs'],
  },
  {
    symbol: 'SubscriptionTeardownLike',
    kind: 'type',
    pageId: 'api-validation-async',
    importPath: MODELS,
    signature: 'type SubscriptionTeardownLike = SubscriptionLike | (() => void) | void',
    en: 'Allowed cleanup result returned by a structural subscribe implementation.',
    vi: 'Kết quả cleanup được phép trả về từ implementation subscribe cấu trúc.',
    returnsEn: 'A subscription object, cleanup callback, or no cleanup value.',
    returnsVi: 'Object subscription, callback cleanup hoặc không có giá trị cleanup.',
    ...typeBoundary(
      'resolveMaybeAsync normalizes the object and function forms and invokes cleanup after settlement.',
      'resolveMaybeAsync chuẩn hóa dạng object và function rồi gọi cleanup sau khi settle.',
      'Returning an invalid non-void cleanup value causes a ValidationError rather than being ignored.',
      'Trả về giá trị cleanup không hợp lệ và không phải void sẽ gây ValidationError thay vì bị bỏ qua.',
    ),
    exampleIds: ['async-rxjs'],
  },
  {
    symbol: 'SubscribableLike',
    kind: 'interface',
    pageId: 'api-validation-async',
    importPath: MODELS,
    signature: 'interface SubscribableLike<T> { subscribe(observerOrNext?: Partial<ObserverLike<T>> | ((value: T) => void), error?: (error: unknown) => void, complete?: () => void): SubscriptionTeardownLike }',
    en: 'Dependency-free structural observable contract supporting observer and callback subscribe forms.',
    vi: 'Contract observable cấu trúc không phụ thuộc thư viện, hỗ trợ cả dạng observer và callback của subscribe.',
    properties: [
      { name: 'subscribe', type: '(observerOrNext?: Partial<ObserverLike<T>> | ((value: T) => void), error?: (error: unknown) => void, complete?: () => void) => SubscriptionTeardownLike', en: 'Subscribes with an observer or callbacks and returns optional cleanup.', vi: 'Đăng ký bằng observer hoặc callback và trả về cleanup tùy chọn.' },
    ],
    returnsEn: 'A subscribable that may return a cleanup callback, subscription handle, or void.',
    returnsVi: 'Subscribable có thể trả callback cleanup, handle subscription hoặc void.',
    ...typeBoundary(
      'Compatible RxJS Observables can be passed structurally without adding RxJS to this package.',
      'Observable RxJS tương thích có thể được truyền theo cấu trúc mà không thêm RxJS vào package.',
      'A callable subscribe property is shape compatibility only; do not treat arbitrary subscribables as a trust boundary.',
      'Thuộc tính subscribe callable chỉ chứng minh tương thích hình dạng; không coi subscribable bất kỳ là biên tin cậy.',
    ),
    exampleIds: ['async-rxjs'],
  },
  {
    symbol: 'MaybeAsync',
    kind: 'type',
    pageId: 'api-validation-async',
    importPath: MODELS,
    signature: 'type MaybeAsync<T> = T | PromiseLike<T> | SubscribableLike<T>',
    en: 'Accepts a plain value, any realm-independent PromiseLike, or a structural subscribable.',
    vi: 'Chấp nhận giá trị thường, PromiseLike không phụ thuộc realm hoặc subscribable cấu trúc.',
    returnsEn: 'A synchronous or supported asynchronous representation of T.',
    returnsVi: 'Biểu diễn đồng bộ hoặc bất đồng bộ được hỗ trợ của T.',
    ...typeBoundary(
      'The union has no RxJS runtime or declaration dependency.',
      'Union không có dependency RxJS ở runtime hay declaration.',
      'Resolve values through resolveMaybeAsync when source errors, empty completion, and cleanup must be handled consistently.',
      'Resolve giá trị qua resolveMaybeAsync khi cần xử lý nhất quán lỗi nguồn, hoàn tất rỗng và cleanup.',
    ),
    exampleIds: ['async-rxjs'],
  },
  {
    symbol: 'isPromiseLike',
    kind: 'function',
    pageId: 'api-validation-async',
    importPath: MODELS,
    signature: 'const isPromiseLike: <T = unknown>(value: unknown) => value is PromiseLike<T>',
    en: 'Checks structurally for a callable Promise/A+ then method across realms.',
    vi: 'Kiểm tra theo cấu trúc method then callable của Promise/A+ xuyên realm.',
    parameters: [
      { name: 'value', type: 'unknown', en: 'Candidate value to inspect.', vi: 'Giá trị ứng viên cần kiểm tra.' },
    ],
    returnsEn: 'true when value is a non-null object or function with a callable then property.',
    returnsVi: 'true khi value là object hoặc function khác null có thuộc tính then callable.',
    runtimeEn: ['This is a structural guard and does not require native Promise instanceof checks.', 'A throwing then getter propagates its original error.'],
    runtimeVi: ['Đây là type guard cấu trúc, không yêu cầu kiểm tra instanceof Promise native.', 'Getter then ném lỗi sẽ truyền nguyên lỗi đó ra ngoài.'],
    securityEn: ['Do not assume a thenable is trusted; invoking its then method executes caller-controlled code.'],
    securityVi: ['Không giả định thenable là tin cậy; gọi method then sẽ chạy code do bên gọi kiểm soát.'],
    exampleIds: ['async-rxjs'],
  },
  {
    symbol: 'isSubscribableLike',
    kind: 'function',
    pageId: 'api-validation-async',
    importPath: MODELS,
    signature: 'const isSubscribableLike: <T = unknown>(value: unknown) => value is SubscribableLike<T>',
    en: 'Checks structurally for a callable subscribe method.',
    vi: 'Kiểm tra theo cấu trúc method subscribe callable.',
    parameters: [
      { name: 'value', type: 'unknown', en: 'Candidate value to inspect.', vi: 'Giá trị ứng viên cần kiểm tra.' },
    ],
    returnsEn: 'true when value is a non-null object or function with a callable subscribe property.',
    returnsVi: 'true khi value là object hoặc function khác null có thuộc tính subscribe callable.',
    runtimeEn: ['Compatible observable libraries satisfy the guard without an imported base class.', 'A throwing subscribe getter propagates its original error.'],
    runtimeVi: ['Các thư viện observable tương thích thỏa guard mà không cần import base class.', 'Getter subscribe ném lỗi sẽ truyền nguyên lỗi đó ra ngoài.'],
    securityEn: ['Shape detection does not sandbox subscribe; subscribing can execute arbitrary source code synchronously.'],
    securityVi: ['Kiểm tra hình dạng không sandbox subscribe; thao tác subscribe có thể chạy code nguồn bất kỳ ngay lập tức.'],
    exampleIds: ['async-rxjs'],
  },
  {
    symbol: 'resolveMaybeAsync',
    kind: 'function',
    pageId: 'api-validation-async',
    importPath: MODELS,
    signature: 'const resolveMaybeAsync: <T>(value: MaybeAsync<T>) => Promise<T>',
    en: 'Resolves a plain value, PromiseLike, or the first structural subscribable emission to a Promise.',
    vi: 'Resolve giá trị thường, PromiseLike hoặc emission đầu tiên của subscribable cấu trúc thành Promise.',
    parameters: [
      { name: 'value', type: 'MaybeAsync<T>', en: 'Value or asynchronous source to resolve.', vi: 'Giá trị hoặc nguồn bất đồng bộ cần resolve.' },
    ],
    returnsEn: 'A Promise for the plain value, fulfilled thenable value, or first emitted value.',
    returnsVi: 'Promise của giá trị thường, giá trị thenable hoàn tất hoặc emission đầu tiên.',
    throws: [
      errorSpec('EmptySubscribableError', 'The source completes before emitting a value.', 'Nguồn hoàn tất trước khi phát giá trị.'),
      errorSpec('ValidationError', 'subscribe() returns a cleanup value outside the structural teardown contract.', 'subscribe() trả giá trị cleanup nằm ngoài contract teardown cấu trúc.'),
    ],
    runtimeEn: ['Always returns a Promise, even when async-shape property access throws.', 'The first emission wins, cleanup runs once, source errors reject, and cleanup errors replace successful settlement.'],
    runtimeVi: ['Luôn trả Promise, kể cả khi truy cập thuộc tính nhận diện async ném lỗi.', 'Emission đầu tiên thắng, cleanup chạy một lần, lỗi nguồn làm reject và lỗi cleanup thay thế kết quả thành công.'],
    securityEn: ['Treat source and cleanup errors as unknown; do not expose their raw contents across a security boundary.'],
    securityVi: ['Coi lỗi nguồn và cleanup là unknown; không làm lộ nội dung thô qua biên bảo mật.'],
    exampleIds: ['async-rxjs'],
  },
  {
    symbol: 'normalizeSubscribable',
    kind: 'function',
    pageId: 'api-validation-async',
    importPath: MODELS,
    signature: 'function normalizeSubscribable<T, TSource extends SubscribableLike<T>>(value: TSource): TSource; function normalizeSubscribable<T>(value: T | PromiseLike<T>): SubscribableLike<T>',
    en: 'Normalizes a plain value or PromiseLike to the structural subscribable contract and preserves an existing subscribable.',
    vi: 'Chuẩn hóa giá trị thường hoặc PromiseLike thành contract subscribable cấu trúc và giữ nguyên subscribable có sẵn.',
    parameters: [
      { name: 'value', type: 'MaybeAsync<T>', en: 'Value or source to expose through subscribe.', vi: 'Giá trị hoặc nguồn cần cung cấp qua subscribe.' },
    ],
    returnsEn: 'A dependency-free SubscribableLike<T>; an existing non-thenable subscribable is returned unchanged with its concrete type.',
    returnsVi: 'SubscribableLike<T> không phụ thuộc thư viện; subscribable có sẵn và không phải thenable được trả nguyên trạng cùng kiểu cụ thể.',
    runtimeEn: ['Plain values emit and complete synchronously when subscribed; promises settle asynchronously.', 'Promise-backed observer callback failures are host-reported through reportError or a microtask throw.'],
    runtimeVi: ['Giá trị thường phát và complete đồng bộ khi subscribe; promise settle bất đồng bộ.', 'Lỗi callback observer với nguồn promise được host-report qua reportError hoặc ném trong microtask.'],
    securityEn: ['Wrapped values and promises intentionally offer no RxJS-only operators; an existing RxJS input retains its concrete operators. Handle callback errors at the application boundary.'],
    securityVi: ['Giá trị và promise được bọc cố ý không cung cấp operator riêng của RxJS; input RxJS có sẵn giữ nguyên operator cụ thể. Hãy xử lý lỗi callback tại biên ứng dụng.'],
    exampleIds: ['async-rxjs'],
    aliases: ['normalizeAsync'],
  },
  {
    symbol: 'normalizeAsync',
    kind: 'function',
    pageId: 'api-validation-async',
    importPath: MODELS,
    signature: 'const normalizeAsync: typeof normalizeSubscribable',
    en: 'Deprecated compatibility alias of normalizeSubscribable with the same structural return contract.',
    vi: 'Alias tương thích đã deprecated của normalizeSubscribable với cùng contract trả về dạng cấu trúc.',
    parameters: [
      { name: 'value', type: 'MaybeAsync<T>', en: 'Value or source to normalize.', vi: 'Giá trị hoặc nguồn cần chuẩn hóa.' },
    ],
    returnsEn: 'Exactly the value returned by normalizeSubscribable.',
    returnsVi: 'Đúng giá trị do normalizeSubscribable trả về.',
    runtimeEn: ['The alias remains callable in v1.2; plain values and promises produce only the structural contract.', 'Existing RxJS Observables are returned unchanged with their concrete type, so methods such as pipe() remain available for those inputs.'],
    runtimeVi: ['Alias vẫn gọi được ở v1.2; giá trị thường và promise chỉ tạo contract cấu trúc.', 'Observable RxJS có sẵn được trả nguyên trạng cùng kiểu cụ thể nên các method như pipe() vẫn dùng được với những input đó.'],
    securityEn: ['For plain values or promises, normalize through application-owned RxJS before calling operators; do not bypass typing with unsafe casts.'],
    securityVi: ['Với giá trị thường hoặc promise, hãy chuẩn hóa qua RxJS do ứng dụng sở hữu trước khi gọi operator; không vượt typing bằng cast không an toàn.'],
    exampleIds: ['async-rxjs'],
    deprecation: deprecated(
      'normalizeSubscribable',
      'Use normalizeSubscribable to make the dependency-free structural return contract explicit.',
      'Dùng normalizeSubscribable để thể hiện rõ contract trả về dạng cấu trúc và không phụ thuộc thư viện.',
    ),
  },
] as const satisfies readonly SymbolSpec[];

const constantSpecs = [
  {
    symbol: 'EMPTY_STR',
    kind: 'constant',
    pageId: 'api-constants',
    importPath: CONSTANTS,
    signature: "const EMPTY_STR: '--'",
    en: 'Default double-dash placeholder used by UI code for empty or null display values.',
    vi: 'Placeholder hai dấu gạch ngang mặc định dùng trong UI để hiển thị giá trị rỗng hoặc null.',
    returnsEn: 'The literal string "--".',
    returnsVi: 'Chuỗi literal "--".',
    runtimeEn: ['The exported primitive is immutable; applying it to a value remains an application display decision.'],
    runtimeVi: ['Primitive export là bất biến; việc áp dụng nó cho giá trị vẫn là quyết định hiển thị của ứng dụng.'],
    securityEn: ['A placeholder is presentation only and must not be confused with redaction, missing-data authorization, or sanitization.'],
    securityVi: ['Placeholder chỉ phục vụ trình bày, không được nhầm với che dữ liệu, phân quyền dữ liệu thiếu hay sanitize.'],
    exampleIds: ['numbers-validation'],
  },
  {
    symbol: 'SD_LANGUAGE_STORAGE_KEY',
    kind: 'constant',
    pageId: 'api-constants',
    importPath: CONSTANTS,
    signature: "const SD_LANGUAGE_STORAGE_KEY: 'sd-core.language'",
    en: 'Stable localStorage key used by SDCoreJS language-aware browser integrations.',
    vi: 'Key localStorage ổn định được các tích hợp trình duyệt SDCoreJS có nhận biết ngôn ngữ sử dụng.',
    returnsEn: 'The literal key "sd-core.language".',
    returnsVi: 'Key literal "sd-core.language".',
    runtimeEn: ['Reading or writing the key requires a runtime with localStorage and may fail under storage restrictions.'],
    runtimeVi: ['Đọc hoặc ghi key cần runtime có localStorage và có thể thất bại khi storage bị hạn chế.'],
    securityEn: ['Store only a locale preference under this key; localStorage is script-readable and unsuitable for secrets or credentials.'],
    securityVi: ['Chỉ lưu lựa chọn locale dưới key này; localStorage có thể bị script đọc và không phù hợp cho bí mật hay credential.'],
    exampleIds: ['browser-workflows'],
  },
  {
    symbol: 'SUPPORTED_LANGUAGES',
    kind: 'constant',
    pageId: 'api-constants',
    importPath: CONSTANTS,
    signature: 'const SUPPORTED_LANGUAGES: readonly Language[]',
    en: 'Ordered catalogue of application locale codes supported by the SDCoreJS language contract.',
    vi: 'Danh mục có thứ tự các mã locale ứng dụng được contract ngôn ngữ SDCoreJS hỗ trợ.',
    returnsEn: "The readonly-typed sequence ['vi', 'en', 'ja', 'ko', 'zh'].",
    returnsVi: "Dãy có kiểu readonly ['vi', 'en', 'ja', 'ko', 'zh'].",
    runtimeEn: ['The readonly annotation is compile-time only; treat the shared runtime array as immutable and clone before application-specific changes.'],
    runtimeVi: ['Annotation readonly chỉ có ở compile time; coi mảng runtime dùng chung là bất biến và clone trước khi tùy biến cho ứng dụng.'],
    securityEn: ['Use membership checking for untrusted locale strings and fall back explicitly; a type assertion does not validate persisted data.'],
    securityVi: ['Kiểm tra membership cho locale không tin cậy và fallback tường minh; ép kiểu không kiểm tra dữ liệu lưu trữ.'],
    exampleIds: ['browser-workflows'],
  },
  {
    symbol: 'OPERATORS',
    kind: 'constant',
    pageId: 'api-constants',
    importPath: CONSTANTS,
    signature: 'const OPERATORS: Array<{ value: Operator; icon: string; display: string }>',
    en: 'Filter-operator metadata for builder UIs, pairing each operator value with a static SVG fragment and localization key.',
    vi: 'Metadata toán tử filter cho UI builder, ghép mỗi giá trị operator với SVG fragment tĩnh và key bản địa hóa.',
    returnsEn: 'A mutable runtime array covering all 17 value-bearing and null-presence operators.',
    returnsVi: 'Mảng runtime có thể thay đổi, bao phủ đủ 17 toán tử có dữ liệu và kiểm tra null.',
    runtimeEn: ['icon contains package-owned inner SVG markup and display contains an i18n lookup key.', 'Clone entries before adding application state so consumers do not mutate the shared export.'],
    runtimeVi: ['icon chứa inner SVG markup do package sở hữu và display chứa key tra cứu i18n.', 'Clone các mục trước khi thêm state ứng dụng để không sửa export dùng chung.'],
    securityEn: ['Do not concatenate untrusted markup into icon or pass arbitrary external SVG through the same rendering path; validate filter values separately.'],
    securityVi: ['Không nối markup không tin cậy vào icon hoặc đưa SVG bên ngoài tùy ý qua cùng luồng render; kiểm tra riêng giá trị filter.'],
    exampleIds: ['strict-filters'],
  },
  {
    symbol: 'VALIDATION_PATTERNS',
    kind: 'constant',
    pageId: 'api-constants',
    importPath: CONSTANTS,
    signature: 'const VALIDATION_PATTERNS: ValidationPattern[]',
    en: 'Built-in metadata catalogue for 22 common, Vietnamese, web, numeric, identifier, color, and Base64 regex patterns.',
    vi: 'Danh mục metadata dựng sẵn cho 22 pattern regex về định dạng phổ biến, Việt Nam, web, số, định danh, màu và Base64.',
    returnsEn: 'A runtime array of ValidationPattern records backed by StringUtilities regex sources.',
    returnsVi: 'Mảng runtime các record ValidationPattern dùng nguồn regex từ StringUtilities.',
    runtimeEn: ['The array is mutable at runtime despite its constant binding; clone before customization.', 'name and errorMessage are localization keys rather than final user-facing strings.'],
    runtimeVi: ['Mảng có thể thay đổi lúc chạy dù binding là const; hãy clone trước khi tùy biến.', 'name và errorMessage là key bản địa hóa, không phải chuỗi cuối hiển thị cho người dùng.'],
    securityEn: ['These patterns check documented syntax only; they do not prove file content, URL safety, identity, ownership, or server-side validity.'],
    securityVi: ['Các pattern chỉ kiểm tra cú pháp đã mô tả; không chứng minh nội dung file, độ an toàn URL, danh tính, quyền sở hữu hay tính hợp lệ phía server.'],
    exampleIds: ['numbers-validation'],
  },
] as const satisfies readonly SymbolSpec[];

const errorSpecs = [
  {
    symbol: 'SdcoreUtilsErrorOptions',
    kind: 'interface',
    pageId: 'api-errors',
    importPath: ERRORS,
    signature: 'interface SdcoreUtilsErrorOptions { cause?: unknown }',
    en: 'Shared constructor options for attaching a lower-level cause to public utility errors.',
    vi: 'Tùy chọn constructor dùng chung để gắn nguyên nhân cấp thấp vào lỗi public của utility.',
    parameters: [
      { name: 'cause', type: 'unknown', optional: true, en: 'Underlying failure preserved as a non-enumerable error property.', vi: 'Lỗi nguyên nhân được giữ trong thuộc tính error không enumerable.' },
    ],
    returnsEn: 'An optional cause container accepted by supporting error constructors.',
    returnsVi: 'Container cause tùy chọn được các constructor lỗi hỗ trợ chấp nhận.',
    ...typeBoundary(
      'When supplied, cause is defined non-enumerably and remains readable as error.cause.',
      'Khi được truyền, cause được định nghĩa non-enumerable và vẫn đọc được qua error.cause.',
      'A cause may contain secrets or transport details; redact it before logging or crossing a trust boundary.',
      'Cause có thể chứa bí mật hoặc chi tiết transport; hãy ẩn trước khi log hay truyền qua biên tin cậy.',
    ),
    exampleIds: ['typed-errors'],
  },
  {
    symbol: 'SdcoreUtilsError',
    kind: 'error',
    pageId: 'api-errors',
    importPath: ERRORS,
    signature: 'class SdcoreUtilsError extends Error { static readonly errorName: string; readonly cause?: unknown; static [Symbol.hasInstance](value: unknown): boolean; constructor(message: string, options?: SdcoreUtilsErrorOptions) }',
    en: 'Base class for failures intentionally raised by @sdcorejs/utils.',
    vi: 'Lớp cơ sở cho các lỗi được @sdcorejs/utils chủ động phát sinh.',
    parameters: [
      { name: 'message', type: 'string', en: 'Human-readable failure message.', vi: 'Thông báo lỗi đọc được.' },
      { name: 'options', type: 'SdcoreUtilsErrorOptions', optional: true, defaultValue: '{}', en: 'Optional lower-level cause.', vi: 'Nguyên nhân cấp thấp tùy chọn.' },
    ],
    returnsEn: 'An Error instance branded for reliable instanceof checks across independently bundled public entry points.',
    returnsVi: 'Instance Error có brand để instanceof ổn định giữa các public entry point được bundle độc lập.',
    runtimeEn: ['The constructor restores the subclass prototype and sets name from the static errorName of the concrete class.', 'A global-symbol brand holding errorName values supplements the native prototype-chain instanceof check, so bundlers that rename class bindings do not break it.', 'A subclass that does not declare its own static errorName throws a TypeError when constructed.'],
    runtimeVi: ['Constructor khôi phục prototype của subclass và đặt name theo static errorName của lớp cụ thể.', 'Brand bằng global symbol chứa các giá trị errorName bổ sung cho kiểm tra instanceof theo prototype chain native, nên bundler đổi tên class cũng không làm hỏng.', 'Subclass không tự khai báo static errorName sẽ ném TypeError khi khởi tạo.'],
    securityEn: ['Catch this base class only for shared handling; use a narrow subclass when recovery differs, and redact message/cause before external display.'],
    securityVi: ['Chỉ catch lớp cơ sở này cho xử lý chung; dùng subclass hẹp khi cách phục hồi khác nhau và ẩn message/cause trước khi hiển thị ra ngoài.'],
    exampleIds: ['typed-errors'],
  },
  {
    symbol: 'SecurityError',
    kind: 'error',
    pageId: 'api-errors',
    importPath: ERRORS,
    signature: 'class SecurityError extends SdcoreUtilsError { constructor(message: string, options?: SdcoreUtilsErrorOptions) }',
    en: 'Base class for operations rejected at an explicit security boundary.',
    vi: 'Lớp cơ sở cho thao tác bị từ chối tại một biên bảo mật tường minh.',
    parameters: [
      { name: 'message', type: 'string', en: 'Security-boundary failure message.', vi: 'Thông báo thất bại tại biên bảo mật.' },
      { name: 'options', type: 'SdcoreUtilsErrorOptions', optional: true, defaultValue: '{}', en: 'Optional underlying cause.', vi: 'Nguyên nhân bên dưới tùy chọn.' },
    ],
    returnsEn: 'A categorized SdcoreUtilsError for security-boundary failures.',
    returnsVi: 'SdcoreUtilsError đã phân loại cho lỗi biên bảo mật.',
    runtimeEn: ['Subclasses include unsafe key/path/URL and cryptographic capability or authentication failures.'],
    runtimeVi: ['Subclass gồm lỗi key/path/URL không an toàn và lỗi khả năng hoặc xác thực mật mã.'],
    securityEn: ['Do not convert SecurityError into an insecure fallback; fail closed or surface a safe, generic recovery path.'],
    securityVi: ['Không chuyển SecurityError thành fallback kém an toàn; hãy fail closed hoặc cung cấp đường phục hồi chung, an toàn.'],
    exampleIds: ['typed-errors'],
  },
  {
    symbol: 'ValidationError',
    kind: 'error',
    pageId: 'api-errors',
    importPath: ERRORS,
    signature: 'class ValidationError extends SdcoreUtilsError { constructor(message: string, options?: SdcoreUtilsErrorOptions) }',
    en: 'Base class for invalid caller arguments, options, or structural input.',
    vi: 'Lớp cơ sở cho đối số, tùy chọn hoặc input cấu trúc không hợp lệ từ bên gọi.',
    parameters: [
      { name: 'message', type: 'string', en: 'Validation failure message.', vi: 'Thông báo validation thất bại.' },
      { name: 'options', type: 'SdcoreUtilsErrorOptions', optional: true, defaultValue: '{}', en: 'Optional underlying cause.', vi: 'Nguyên nhân bên dưới tùy chọn.' },
    ],
    returnsEn: 'A categorized SdcoreUtilsError for invalid input.',
    returnsVi: 'SdcoreUtilsError đã phân loại cho input không hợp lệ.',
    runtimeEn: ['Many narrow public errors inherit this class while preserving cross-entry-point instanceof behavior.'],
    runtimeVi: ['Nhiều lỗi public hẹp kế thừa lớp này và vẫn giữ instanceof xuyên entry point.'],
    securityEn: ['Escape messages before rendering them and do not assume catching validation errors replaces trusted-server validation.'],
    securityVi: ['Escape thông báo trước khi render và không giả định catch validation error thay thế kiểm tra ở server tin cậy.'],
    exampleIds: ['typed-errors'],
  },
  {
    symbol: 'SerializationError',
    kind: 'error',
    pageId: 'api-errors',
    importPath: ERRORS,
    signature: 'class SerializationError extends SdcoreUtilsError { constructor(message: string, options?: SdcoreUtilsErrorOptions) }',
    en: 'Base class for deterministic serialization-domain failures.',
    vi: 'Lớp cơ sở cho lỗi miền tuần tự hóa có tính xác định.',
    parameters: [
      { name: 'message', type: 'string', en: 'Serialization failure message.', vi: 'Thông báo tuần tự hóa thất bại.' },
      { name: 'options', type: 'SdcoreUtilsErrorOptions', optional: true, defaultValue: '{}', en: 'Optional underlying cause.', vi: 'Nguyên nhân bên dưới tùy chọn.' },
    ],
    returnsEn: 'A categorized SdcoreUtilsError for unsupported deterministic serialization.',
    returnsVi: 'SdcoreUtilsError đã phân loại cho tuần tự hóa xác định không được hỗ trợ.',
    runtimeEn: ['UnsupportedSerializationTypeError is the current narrow public subclass.'],
    runtimeVi: ['UnsupportedSerializationTypeError là subclass public hẹp hiện tại.'],
    securityEn: ['Do not silently stringify unsupported values or class instances; select a documented serialization domain explicitly.'],
    securityVi: ['Không tự stringify giá trị không hỗ trợ hoặc class instance; hãy chọn rõ miền tuần tự hóa đã được mô tả.'],
    exampleIds: ['typed-errors', 'canonical-hashing'],
  },
  {
    symbol: 'UnsafeObjectKeyError',
    kind: 'error',
    pageId: 'api-errors',
    importPath: ERRORS,
    signature: 'class UnsafeObjectKeyError extends SecurityError { readonly key: string; constructor(key: string) }',
    en: 'Signals that an object key could alter or expose a JavaScript prototype.',
    vi: 'Báo hiệu một key object có thể thay đổi hoặc làm lộ prototype JavaScript.',
    parameters: [
      { name: 'key', type: 'string', en: 'Rejected prototype-sensitive key, preserved on the error.', vi: 'Key nhạy cảm với prototype bị từ chối và được giữ trên error.' },
    ],
    returnsEn: 'A SecurityError whose key property identifies the rejected key.',
    returnsVi: 'SecurityError có thuộc tính key chỉ ra key bị từ chối.',
    runtimeEn: ['Raised for dangerous keys such as __proto__, prototype, or constructor at protected object-building boundaries.'],
    runtimeVi: ['Được ném cho key nguy hiểm như __proto__, prototype hoặc constructor tại các biên tạo object được bảo vệ.'],
    securityEn: ['Reject the input; do not strip the key and continue with a partially trusted object. Escape the key before display.'],
    securityVi: ['Từ chối input; không xóa key rồi tiếp tục với object chỉ được tin một phần. Escape key trước khi hiển thị.'],
    exampleIds: ['typed-errors', 'safe-objects'],
  },
  {
    symbol: 'UnsafePropertyPathError',
    kind: 'error',
    pageId: 'api-errors',
    importPath: ERRORS,
    signature: 'class UnsafePropertyPathError extends SecurityError { readonly path: string; constructor(path: string, reason: string) }',
    en: 'Signals a malformed, excessively deep, accessor-sensitive, or prototype-sensitive property path.',
    vi: 'Báo hiệu đường dẫn thuộc tính sai, quá sâu, nhạy với accessor hoặc prototype.',
    parameters: [
      { name: 'path', type: 'string', en: 'Rejected property path, preserved on the error.', vi: 'Đường dẫn thuộc tính bị từ chối và được giữ trên error.' },
      { name: 'reason', type: 'string', en: 'Safe-path parser reason included in the message.', vi: 'Lý do từ bộ phân tích safe-path được đưa vào message.' },
    ],
    returnsEn: 'A SecurityError whose path property identifies the rejected path.',
    returnsVi: 'SecurityError có thuộc tính path chỉ ra đường dẫn bị từ chối.',
    runtimeEn: ['Protected traversal reads bounded own data properties and rejects prototype-sensitive segments.'],
    runtimeVi: ['Traversal được bảo vệ chỉ đọc own data property có giới hạn và từ chối segment nhạy cảm với prototype.'],
    securityEn: ['Do not retry with unrestricted property traversal. Treat the path as untrusted text when logging or rendering.'],
    securityVi: ['Không thử lại bằng traversal không giới hạn. Coi path là văn bản không tin cậy khi log hoặc render.'],
    exampleIds: ['typed-errors', 'safe-objects'],
  },
  {
    symbol: 'CircularReferenceError',
    kind: 'error',
    pageId: 'api-errors',
    importPath: ERRORS,
    signature: 'class CircularReferenceError extends ValidationError { constructor(path?: string) }',
    en: 'Signals a cycle in an input graph for an API whose documented encoding domain is acyclic.',
    vi: 'Báo hiệu chu trình trong graph input của API có miền mã hóa được mô tả là không chu trình.',
    parameters: [
      { name: 'path', type: 'string', optional: true, en: 'Optional location of the detected cycle.', vi: 'Vị trí chu trình phát hiện được, nếu có.' },
    ],
    returnsEn: 'A ValidationError with an optional cycle location in its message.',
    returnsVi: 'ValidationError có thể chứa vị trí chu trình trong message.',
    runtimeEn: ['Raised by serializers that reject cycles; ObjectUtilities.clone separately preserves cyclic object graphs.'],
    runtimeVi: ['Được ném bởi serializer từ chối chu trình; ObjectUtilities.clone có contract riêng bảo toàn graph object có chu trình.'],
    securityEn: ['Choose an explicitly cycle-aware representation instead of silently dropping repeated references.'],
    securityVi: ['Chọn biểu diễn có nhận biết chu trình tường minh thay vì âm thầm bỏ tham chiếu lặp.',],
    exampleIds: ['typed-errors', 'canonical-hashing'],
  },
  {
    symbol: 'UnsupportedSerializationTypeError',
    kind: 'error',
    pageId: 'api-errors',
    importPath: ERRORS,
    signature: 'class UnsupportedSerializationTypeError extends SerializationError { readonly valueType: string; constructor(valueType: string, path?: string) }',
    en: 'Signals a JavaScript value outside the selected serializer’s documented domain.',
    vi: 'Báo hiệu giá trị JavaScript nằm ngoài miền được serializer đã chọn hỗ trợ.',
    parameters: [
      { name: 'valueType', type: 'string', en: 'Stable description of the unsupported JavaScript type.', vi: 'Mô tả ổn định của kiểu JavaScript không được hỗ trợ.' },
      { name: 'path', type: 'string', optional: true, en: 'Optional location of the value in the input graph.', vi: 'Vị trí giá trị trong graph input, nếu có.' },
    ],
    returnsEn: 'A SerializationError exposing the rejected valueType.',
    returnsVi: 'SerializationError cung cấp valueType bị từ chối.',
    runtimeEn: ['stableStringify and canonicalStringify deliberately support different value domains; neither silently serializes arbitrary class instances.'],
    runtimeVi: ['stableStringify và canonicalStringify cố ý hỗ trợ miền giá trị khác nhau; không API nào âm thầm serialize class instance tùy ý.'],
    securityEn: ['Do not replace the failure with implicit toString or lossy JSON coercion when canonical output is security-relevant.'],
    securityVi: ['Không thay lỗi bằng toString ngầm hoặc ép JSON mất dữ liệu khi output canonical liên quan đến bảo mật.'],
    exampleIds: ['typed-errors', 'canonical-hashing'],
  },
  {
    symbol: 'WebCryptoUnavailableError',
    kind: 'error',
    pageId: 'api-errors',
    importPath: ERRORS,
    signature: 'class WebCryptoUnavailableError extends SecurityError { constructor() }',
    en: 'Signals that an operation requires the Web Crypto API but the runtime does not provide it.',
    vi: 'Báo hiệu thao tác cần Web Crypto API nhưng runtime không cung cấp.',
    returnsEn: 'A SecurityError with a capability-focused, non-secret message.',
    returnsVi: 'SecurityError có thông báo tập trung vào capability và không chứa bí mật.',
    runtimeEn: ['Cryptographic hashing and AES operations fail explicitly when the required Web Crypto capability is absent.'],
    runtimeVi: ['Hash mật mã và thao tác AES thất bại tường minh khi thiếu capability Web Crypto cần thiết.'],
    securityEn: ['Fail closed or move the operation to a supported runtime; never substitute legacy obfuscation or unauthenticated crypto.'],
    securityVi: ['Fail closed hoặc chuyển thao tác sang runtime được hỗ trợ; không thay bằng obfuscation cũ hay crypto không xác thực.'],
    exampleIds: ['typed-errors', 'aes-gcm'],
  },
  {
    symbol: 'SecureRandomUnavailableError',
    kind: 'error',
    pageId: 'api-errors',
    importPath: ERRORS,
    signature: 'class SecureRandomUnavailableError extends SecurityError { constructor(options?: SdcoreUtilsErrorOptions) }',
    en: 'Signals that cryptographically secure randomness is unavailable.',
    vi: 'Báo hiệu nguồn ngẫu nhiên an toàn về mật mã không khả dụng.',
    parameters: [
      { name: 'options', type: 'SdcoreUtilsErrorOptions', optional: true, defaultValue: '{}', en: 'Optional lower-level capability failure.', vi: 'Lỗi capability cấp thấp tùy chọn.' },
    ],
    returnsEn: 'A SecurityError preserving an optional lower-level cause.',
    returnsVi: 'SecurityError giữ cause cấp thấp tùy chọn.',
    runtimeEn: ['Secure UUID generation and other randomness-dependent operations use this typed failure rather than weak fallback randomness.'],
    runtimeVi: ['Sinh UUID an toàn và thao tác cần ngẫu nhiên dùng lỗi có kiểu này thay vì fallback ngẫu nhiên yếu.'],
    securityEn: ['Never replace this failure with Math.random for identifiers, IVs, keys, tokens, or other security-sensitive values.'],
    securityVi: ['Không thay lỗi này bằng Math.random cho định danh, IV, key, token hoặc giá trị nhạy cảm bảo mật khác.'],
    exampleIds: ['typed-errors', 'aes-gcm'],
  },
  {
    symbol: 'EncryptionFormatError',
    kind: 'error',
    pageId: 'api-errors',
    importPath: ERRORS,
    signature: 'class EncryptionFormatError extends ValidationError { constructor(message: string, options?: SdcoreUtilsErrorOptions) }',
    en: 'Signals a malformed, unsupported, or incorrectly versioned authenticated-encryption token.',
    vi: 'Báo hiệu token mã hóa có xác thực bị sai cấu trúc, không hỗ trợ hoặc sai version.',
    parameters: [
      { name: 'message', type: 'string', en: 'Token-format failure message.', vi: 'Thông báo lỗi định dạng token.' },
      { name: 'options', type: 'SdcoreUtilsErrorOptions', optional: true, defaultValue: '{}', en: 'Optional parsing cause.', vi: 'Nguyên nhân phân tích tùy chọn.' },
    ],
    returnsEn: 'A ValidationError distinguishing token syntax/version failure from authentication failure.',
    returnsVi: 'ValidationError phân biệt lỗi cú pháp/version token với lỗi xác thực.',
    runtimeEn: ['Thrown before a malformed or unsupported AES-GCM envelope can be processed as a valid token.'],
    runtimeVi: ['Được ném trước khi envelope AES-GCM sai hoặc không hỗ trợ có thể bị xử lý như token hợp lệ.'],
    securityEn: ['Reject the token and return a generic client response; do not reinterpret legacy obfuscation as AES-GCM input.'],
    securityVi: ['Từ chối token và trả response chung cho client; không diễn giải obfuscation cũ thành input AES-GCM.'],
    exampleIds: ['typed-errors', 'aes-gcm'],
  },
  {
    symbol: 'EncryptionAuthenticationError',
    kind: 'error',
    pageId: 'api-errors',
    importPath: ERRORS,
    signature: 'class EncryptionAuthenticationError extends SecurityError { constructor(options?: SdcoreUtilsErrorOptions) }',
    en: 'Signals authenticated decryption failure without exposing plaintext, key, or cryptographic detail.',
    vi: 'Báo hiệu giải mã có xác thực thất bại mà không làm lộ plaintext, key hay chi tiết mật mã.',
    parameters: [
      { name: 'options', type: 'SdcoreUtilsErrorOptions', optional: true, defaultValue: '{}', en: 'Optional lower-level cryptographic cause.', vi: 'Nguyên nhân mật mã cấp thấp tùy chọn.' },
    ],
    returnsEn: 'A SecurityError with the fixed message "Authenticated decryption failed".',
    returnsVi: 'SecurityError có message cố định "Authenticated decryption failed".',
    runtimeEn: ['A wrong key, changed ciphertext/IV, or mismatched additional authenticated data reaches this same public failure category.'],
    runtimeVi: ['Sai key, ciphertext/IV bị đổi hoặc additional authenticated data không khớp đều tới cùng nhóm lỗi public này.'],
    securityEn: ['Do not expose the nested cause or branch external responses by cryptographic detail; reject the token without insecure retry.'],
    securityVi: ['Không làm lộ cause lồng nhau hay phân nhánh response ngoài theo chi tiết mật mã; từ chối token, không retry kém an toàn.'],
    exampleIds: ['typed-errors', 'aes-gcm'],
  },
  {
    symbol: 'FilterValidationError',
    kind: 'error',
    pageId: 'api-errors',
    importPath: ERRORS,
    signature: 'class FilterValidationError extends ValidationError { constructor(message: string, options?: SdcoreUtilsErrorOptions) }',
    en: 'Signals a malformed filter shape, operand, option, range, graph, or declared coercion.',
    vi: 'Báo hiệu hình dạng, toán hạng, tùy chọn, khoảng, graph hoặc ép kiểu khai báo của filter bị sai.',
    parameters: [
      { name: 'message', type: 'string', en: 'Specific filter validation failure.', vi: 'Lỗi kiểm tra filter cụ thể.' },
      { name: 'options', type: 'SdcoreUtilsErrorOptions', optional: true, defaultValue: '{}', en: 'Optional underlying cause.', vi: 'Nguyên nhân bên dưới tùy chọn.' },
    ],
    returnsEn: 'A ValidationError for strict filter-definition failures.',
    returnsVi: 'ValidationError cho lỗi định nghĩa filter nghiêm ngặt.',
    runtimeEn: ['Malformed definitions throw; a valid definition evaluated against invalid entity field data produces a deterministic non-match.'],
    runtimeVi: ['Định nghĩa sai sẽ ném lỗi; định nghĩa hợp lệ đánh giá trên dữ liệu field entity sai sẽ cho kết quả không khớp xác định.'],
    securityEn: ['Treat the filter as invalid configuration and enforce actual row/field authorization again on the trusted server.'],
    securityVi: ['Coi filter là cấu hình không hợp lệ và thực thi lại phân quyền row/field thực sự ở server tin cậy.'],
    exampleIds: ['typed-errors', 'strict-filters'],
  },
  {
    symbol: 'DateParseError',
    kind: 'error',
    pageId: 'api-errors',
    importPath: ERRORS,
    signature: 'class DateParseError extends ValidationError { constructor(message: string, options?: SdcoreUtilsErrorOptions) }',
    en: 'Signals failure to parse or calculate a strict calendar date, local date-time, or instant.',
    vi: 'Báo hiệu thất bại khi parse hoặc tính ngày lịch, date-time local hay instant theo chế độ nghiêm ngặt.',
    parameters: [
      { name: 'message', type: 'string', en: 'Strict date failure message.', vi: 'Thông báo lỗi ngày nghiêm ngặt.' },
      { name: 'options', type: 'SdcoreUtilsErrorOptions', optional: true, defaultValue: '{}', en: 'Optional underlying cause.', vi: 'Nguyên nhân bên dưới tùy chọn.' },
    ],
    returnsEn: 'A ValidationError for invalid date syntax, overflow, or rejected arithmetic policy.',
    returnsVi: 'ValidationError cho cú pháp ngày sai, overflow hoặc chính sách tính toán bị từ chối.',
    runtimeEn: ['Strict APIs reject overflow and ambiguous inputs instead of relying on permissive Date normalization.'],
    runtimeVi: ['API nghiêm ngặt từ chối overflow và input mơ hồ thay vì dựa vào Date normalization dễ dãi.'],
    securityEn: ['Ask for corrected input or apply an explicit documented policy; do not silently reinterpret a rejected date in regulated workflows.'],
    securityVi: ['Yêu cầu sửa input hoặc áp dụng chính sách đã mô tả tường minh; không tự diễn giải lại ngày bị từ chối trong workflow được quản lý.'],
    exampleIds: ['typed-errors', 'dates-dst'],
  },
  {
    symbol: 'PagingResponseError',
    kind: 'error',
    pageId: 'api-errors',
    importPath: ERRORS,
    signature: 'class PagingResponseError extends ValidationError { constructor(message: string, options?: SdcoreUtilsErrorOptions) }',
    en: 'Signals a malformed, inconsistent, or non-progressing page response.',
    vi: 'Báo hiệu response phân trang sai cấu trúc, không nhất quán hoặc không tiến triển.',
    parameters: [
      { name: 'message', type: 'string', en: 'Paging-response invariant that failed.', vi: 'Invariant của response phân trang bị vi phạm.' },
      { name: 'options', type: 'SdcoreUtilsErrorOptions', optional: true, defaultValue: '{}', en: 'Optional transport or validation cause.', vi: 'Nguyên nhân transport hoặc validation tùy chọn.' },
    ],
    returnsEn: 'A ValidationError indicating that fetching cannot continue safely.',
    returnsVi: 'ValidationError cho biết không thể tiếp tục fetch an toàn.',
    runtimeEn: ['fetchAllByPaging validates every page shape, forward progress, and total-count policy before accumulating results; duplicate item values remain valid data.'],
    runtimeVi: ['fetchAllByPaging kiểm tra cấu trúc từng trang, tiến triển và chính sách total trước khi tích lũy; giá trị item trùng nhau vẫn là dữ liệu hợp lệ.'],
    securityEn: ['Stop the loop and investigate the endpoint; do not return partial data as if the fetch completed successfully.'],
    securityVi: ['Dừng vòng lặp và kiểm tra endpoint; không trả dữ liệu một phần như thể fetch đã hoàn tất thành công.'],
    exampleIds: ['typed-errors', 'paging-zero'],
  },
  {
    symbol: 'PagingLimitError',
    kind: 'error',
    pageId: 'api-errors',
    importPath: ERRORS,
    signature: 'class PagingLimitError extends ValidationError { constructor(message: string, options?: SdcoreUtilsErrorOptions) }',
    en: 'Signals that pagination reached a configured page cap or safe-integer boundary.',
    vi: 'Báo hiệu phân trang đã đạt giới hạn trang cấu hình hoặc biên số nguyên an toàn.',
    parameters: [
      { name: 'message', type: 'string', en: 'Limit condition that stopped pagination.', vi: 'Điều kiện giới hạn đã dừng phân trang.' },
      { name: 'options', type: 'SdcoreUtilsErrorOptions', optional: true, defaultValue: '{}', en: 'Optional underlying cause.', vi: 'Nguyên nhân bên dưới tùy chọn.' },
    ],
    returnsEn: 'A ValidationError preventing an unbounded or unsafe paging loop.',
    returnsVi: 'ValidationError ngăn vòng lặp phân trang không giới hạn hoặc không an toàn.',
    runtimeEn: ['fetchAllByPaging starts at page 0 and enforces maxPages plus safe-integer page progression.'],
    runtimeVi: ['fetchAllByPaging bắt đầu tại trang 0 và thực thi maxPages cùng tiến trình page là số nguyên an toàn.'],
    securityEn: ['Choose maxPages from an explicit workload budget; do not raise it blindly in response to an unexpected endpoint.'],
    securityVi: ['Chọn maxPages theo ngân sách workload tường minh; không tăng mù quáng khi endpoint có hành vi bất ngờ.'],
    exampleIds: ['typed-errors', 'paging-zero'],
  },
  {
    symbol: 'FilePickerCancelledError',
    kind: 'error',
    pageId: 'api-errors',
    importPath: ERRORS,
    signature: 'class FilePickerCancelledError extends ValidationError { constructor() }',
    en: 'Signals that a native file picker closed without a selected file.',
    vi: 'Báo hiệu file picker native đóng mà không có file được chọn.',
    returnsEn: 'A ValidationError with the fixed message "File selection was cancelled".',
    returnsVi: 'ValidationError có message cố định "File selection was cancelled".',
    runtimeEn: ['BrowserUtilities.upload rejects with this typed error for the expected cancellation path and cleans up its temporary input.'],
    runtimeVi: ['BrowserUtilities.upload reject bằng lỗi có kiểu này cho luồng hủy dự kiến và cleanup input tạm.'],
    securityEn: ['Handle cancellation as a neutral user action; still validate any subsequently selected file on a trusted server.'],
    securityVi: ['Xử lý hủy như hành động trung tính của người dùng; vẫn kiểm tra file được chọn sau đó trên server tin cậy.'],
    exampleIds: ['typed-errors', 'browser-workflows'],
  },
  {
    symbol: 'UnsafeUrlProtocolError',
    kind: 'error',
    pageId: 'api-errors',
    importPath: ERRORS,
    signature: 'class UnsafeUrlProtocolError extends SecurityError { readonly protocol: string; constructor(protocol: string) }',
    en: 'Signals that a navigation or download URL uses a missing or disallowed protocol.',
    vi: 'Báo hiệu URL điều hướng hoặc download dùng protocol bị thiếu hoặc không được phép.',
    parameters: [
      { name: 'protocol', type: 'string', en: 'Rejected URL protocol, preserved on the error.', vi: 'Protocol URL bị từ chối và được giữ trên error.' },
    ],
    returnsEn: 'A SecurityError whose protocol property identifies the rejected scheme.',
    returnsVi: 'SecurityError có thuộc tính protocol chỉ ra scheme bị từ chối.',
    runtimeEn: ['Browser downloads allow documented schemes; data: requires opt-in and additional schemes require an explicit reviewed allowlist.'],
    runtimeVi: ['Download trình duyệt cho phép các scheme đã mô tả; data: cần opt-in và scheme bổ sung cần allowlist được rà soát tường minh.'],
    securityEn: ['Do not navigate after catching this error. Keep active schemes such as javascript: rejected and escape the protocol before display.'],
    securityVi: ['Không điều hướng sau khi catch lỗi này. Tiếp tục từ chối scheme chủ động như javascript: và escape protocol trước khi hiển thị.'],
    exampleIds: ['typed-errors', 'browser-workflows'],
  },
  {
    symbol: 'EmptySubscribableError',
    kind: 'error',
    pageId: 'api-errors',
    importPath: ERRORS,
    signature: 'class EmptySubscribableError extends ValidationError { constructor() }',
    en: 'Signals that a subscribable completed before producing the first value requested by resolveMaybeAsync.',
    vi: 'Báo hiệu subscribable hoàn tất trước khi phát giá trị đầu tiên mà resolveMaybeAsync yêu cầu.',
    returnsEn: 'A ValidationError with the fixed message "The subscribable completed without emitting a value".',
    returnsVi: 'ValidationError có message cố định "The subscribable completed without emitting a value".',
    runtimeEn: ['resolveMaybeAsync rejects rather than hanging or resolving undefined, and runs available subscription cleanup once.'],
    runtimeVi: ['resolveMaybeAsync reject thay vì treo hoặc resolve undefined, đồng thời chạy cleanup subscription khả dụng đúng một lần.'],
    securityEn: ['Handle an empty source explicitly as absence or failure according to application policy; do not fabricate privileged data.'],
    securityVi: ['Xử lý nguồn rỗng tường minh là thiếu dữ liệu hoặc thất bại theo chính sách ứng dụng; không tạo dữ liệu đặc quyền giả.'],
    exampleIds: ['typed-errors', 'async-rxjs'],
  },
] as const satisfies readonly SymbolSpec[];

const allSpecs = [...modelSpecs, ...asyncSpecs, ...constantSpecs, ...errorSpecs] as const;

export const CORE_DOCUMENTED_SYMBOLS = [
  'NestedKeyOf',
  'Operator',
  'OperatorHasData',
  'OperatorNoData',
  'Filter',
  'FilterDataType',
  'FilterTimestampUnit',
  'DateRelative',
  'FilterLiteral',
  'FilterHasDataAbsolute',
  'FilterHasDataField',
  'FilterHasDataToday',
  'FilterHasDataRelative',
  'FilterHasData',
  'FilterBetween',
  'FilterNoData',
  'FilterAndOr',
  'FilterFieldType',
  'ValidatedFilter',
  'MatchOptions',
  'Order',
  'QueryReq',
  'PagingReq',
  'PagingRes',
  'Size',
  'Color',
  'MaterialIconFontSet',
  'MaterialSymbolFontSet',
  'ValidationPatternType',
  'ValidationPattern',
  'Language',
  'SubscriptionLike',
  'ObserverLike',
  'SubscriptionTeardownLike',
  'SubscribableLike',
  'MaybeAsync',
  'isPromiseLike',
  'isSubscribableLike',
  'resolveMaybeAsync',
  'normalizeSubscribable',
  'normalizeAsync',
  'EMPTY_STR',
  'SD_LANGUAGE_STORAGE_KEY',
  'SUPPORTED_LANGUAGES',
  'OPERATORS',
  'VALIDATION_PATTERNS',
  'SdcoreUtilsErrorOptions',
  'SdcoreUtilsError',
  'SecurityError',
  'ValidationError',
  'SerializationError',
  'UnsafeObjectKeyError',
  'UnsafePropertyPathError',
  'CircularReferenceError',
  'UnsupportedSerializationTypeError',
  'WebCryptoUnavailableError',
  'SecureRandomUnavailableError',
  'EncryptionFormatError',
  'EncryptionAuthenticationError',
  'FilterValidationError',
  'DateParseError',
  'PagingResponseError',
  'PagingLimitError',
  'FilePickerCancelledError',
  'UnsafeUrlProtocolError',
  'EmptySubscribableError',
] as const;

type CoreDocumentedSymbol = (typeof CORE_DOCUMENTED_SYMBOLS)[number];

export const CORE_IMPORT_PATHS = {
  NestedKeyOf: MODELS,
  Operator: MODELS,
  OperatorHasData: MODELS,
  OperatorNoData: MODELS,
  Filter: MODELS,
  FilterDataType: MODELS,
  FilterTimestampUnit: MODELS,
  DateRelative: MODELS,
  FilterLiteral: MODELS,
  FilterHasDataAbsolute: MODELS,
  FilterHasDataField: MODELS,
  FilterHasDataToday: MODELS,
  FilterHasDataRelative: MODELS,
  FilterHasData: MODELS,
  FilterBetween: MODELS,
  FilterNoData: MODELS,
  FilterAndOr: MODELS,
  FilterFieldType: MODELS,
  ValidatedFilter: MODELS,
  MatchOptions: MODELS,
  Order: MODELS,
  QueryReq: MODELS,
  PagingReq: MODELS,
  PagingRes: MODELS,
  Size: MODELS,
  Color: MODELS,
  MaterialIconFontSet: MODELS,
  MaterialSymbolFontSet: MODELS,
  ValidationPatternType: MODELS,
  ValidationPattern: MODELS,
  Language: MODELS,
  SubscriptionLike: MODELS,
  ObserverLike: MODELS,
  SubscriptionTeardownLike: MODELS,
  SubscribableLike: MODELS,
  MaybeAsync: MODELS,
  isPromiseLike: MODELS,
  isSubscribableLike: MODELS,
  resolveMaybeAsync: MODELS,
  normalizeSubscribable: MODELS,
  normalizeAsync: MODELS,
  EMPTY_STR: CONSTANTS,
  SD_LANGUAGE_STORAGE_KEY: CONSTANTS,
  SUPPORTED_LANGUAGES: CONSTANTS,
  OPERATORS: CONSTANTS,
  VALIDATION_PATTERNS: CONSTANTS,
  SdcoreUtilsErrorOptions: ERRORS,
  SdcoreUtilsError: ERRORS,
  SecurityError: ERRORS,
  ValidationError: ERRORS,
  SerializationError: ERRORS,
  UnsafeObjectKeyError: ERRORS,
  UnsafePropertyPathError: ERRORS,
  CircularReferenceError: ERRORS,
  UnsupportedSerializationTypeError: ERRORS,
  WebCryptoUnavailableError: ERRORS,
  SecureRandomUnavailableError: ERRORS,
  EncryptionFormatError: ERRORS,
  EncryptionAuthenticationError: ERRORS,
  FilterValidationError: ERRORS,
  DateParseError: ERRORS,
  PagingResponseError: ERRORS,
  PagingLimitError: ERRORS,
  FilePickerCancelledError: ERRORS,
  UnsafeUrlProtocolError: ERRORS,
  EmptySubscribableError: ERRORS,
} as const satisfies Readonly<Record<CoreDocumentedSymbol, CanonicalImportPath>>;

export const CORE_API_ENTRIES: readonly ApiEntry[] = Object.freeze(
  allSpecs.map((spec) => createEntry(spec)),
);
